program Project1;

uses
  Forms,
  FORM_GRAVA_PAGAMENTO_PACIENTE_PARCELADO in 'FORM_GRAVA_PAGAMENTO_PACIENTE_PARCELADO.pas' {FORM_GRAVA_PAGAMENTO_PARCELADO},
  UNIT_CAIXA in 'UNIT_CAIXA.pas' {FORM_CAIXA},
  Unit_CONS_AGENDAMENTO in 'Unit_CONS_AGENDAMENTO.pas' {Form_CONS_AGENDAMENTO},
  Unit_CONS_PAGAM_APRAZO in 'Unit_CONS_PAGAM_APRAZO.pas' {Form_CONS_PAGAM_APRAZO},
  Unit_CONS_PAGAM_AVISTA in 'Unit_CONS_PAGAM_AVISTA.pas' {Form_CONS_PAGAM_AVISTA},
  UNIT_CONS_PAGAM_PARCELADO in 'UNIT_CONS_PAGAM_PARCELADO.pas' {Form_CONS_PAGAM_PARCELADO},
  UNIT_CONSULTA_ALTERA_DENTISTA in 'UNIT_CONSULTA_ALTERA_DENTISTA.pas' {FORM_CONSULTA_ALTERA_DENTISTA},
  UNIT_CONSULTA_ALTERA_TRATAMENTOS in 'UNIT_CONSULTA_ALTERA_TRATAMENTOS.pas' {FORM_CONSULTA_ALTERA_TRATAMENTO},
  Unit_CONSULTA_DENTISTA in 'Unit_CONSULTA_DENTISTA.pas' {Form_CONSULTA_DENTISTA},
  Unit_DESPESAS in 'Unit_DESPESAS.pas' {Form_DESPESAS},
  UNIT_ERRO in 'UNIT_ERRO.pas' {FORM_ERRO},
  Unit_ESCOLHE_PAGAMENTO in 'Unit_ESCOLHE_PAGAMENTO.pas' {Form_ESCOLHE_PAGAMENTO},
  Unit_FUNCIONARIOS in 'Unit_FUNCIONARIOS.pas' {Form_FUNCIONARIOS},
  UNIT_GRAVA_AGENDAMENTO in 'UNIT_GRAVA_AGENDAMENTO.pas' {FORM_GRAVA_AGENDAMENTO},
  UNIT_GRAVA_CONSULTA in 'UNIT_GRAVA_CONSULTA.pas' {FORM_GRAVA_CONSULTA},
  UNIT_GRAVA_DENTISTA in 'UNIT_GRAVA_DENTISTA.pas' {FORM_GRAVA_DENTISTA},
  UNIT_GRAVA_FINANCAS in 'UNIT_GRAVA_FINANCAS.pas' {FORM_GRAVA_FINANCAS},
  UNIT_GRAVA_FUNCIONARIO in 'UNIT_GRAVA_FUNCIONARIO.pas' {FORM_GRAVA_FUNCIONARIO},
  UNIT_GRAVA_PACIENTE in 'UNIT_GRAVA_PACIENTE.pas' {FORM_GRAVA_PACIENTE},
  UNIT_GRAVA_PAGAMENTO_DENTISTA in 'UNIT_GRAVA_PAGAMENTO_DENTISTA.pas' {FORM_GRAVA_PAGAMENTO_DENTISTA},
  UNIT_GRAVA_PAGAMENTO_FUNCIONARIO in 'UNIT_GRAVA_PAGAMENTO_FUNCIONARIO.pas' {FORM_GRAVA_PAGAMENTO_FUNCIONARIO},
  UNIT_GRAVA_PAGAMENTO_PACIENTE_APRAZO in 'UNIT_GRAVA_PAGAMENTO_PACIENTE_APRAZO.pas' {FORM_GRAVA_PAGAMENTO_APRAZO},
  UNIT_GRAVA_PAGAMENTO_PACIENTE_AVISTA in 'UNIT_GRAVA_PAGAMENTO_PACIENTE_AVISTA.pas' {FORM_GRAVA_PAGAMENTO_AVISTA},
  UNIT_GRAVA_RESPONSAVEL in 'UNIT_GRAVA_RESPONSAVEL.pas' {FORM_GRAVA_RESPONSAVEL},
  UNIT_GRAVA_TRATAMENTO in 'UNIT_GRAVA_TRATAMENTO.pas' {FORM_GRAVA_TRATAMENTO},
  UNIT_GRAVA_USUARIO in 'UNIT_GRAVA_USUARIO.pas' {FORM_GRAVA_USUARIO},
  UNIT_LOG in 'UNIT_LOG.pas' {FORM_LOG},
  Unit_LOGIN in 'Unit_LOGIN.pas' {Form1},
  Unit_MARCAR_CONSULTA in 'Unit_MARCAR_CONSULTA.pas' {Form_MARCA_CONSULTA},
  Unit_PACIENTES in 'Unit_PACIENTES.pas' {Form_PACIENTE},
  UNIT_PAGAMENTO_DENTISTA in 'UNIT_PAGAMENTO_DENTISTA.pas' {FORM_PAGAMENTO_DENTISTA},
  Unit_PAGAR_FUNCIONARIO in 'Unit_PAGAR_FUNCIONARIO.pas' {Form_PAG_FUNCIONARIO},
  Unit_PRODUTOS in 'Unit_PRODUTOS.pas' {Form_PRODUTOS},
  UNIT_RECUPERA_SENHA in 'UNIT_RECUPERA_SENHA.pas' {FORM_RECUPERA_SENHA},
  Unit_RESPONSAVEL in 'Unit_RESPONSAVEL.pas' {Form_RESPONSAVEL},
  UNIT_SELECIONA_AGENDAMENTO in 'UNIT_SELECIONA_AGENDAMENTO.pas' {FORM_SELECIONA_AGENDAMENTO},
  UNIT_SELECIONA_RESPONSAVEL in 'UNIT_SELECIONA_RESPONSAVEL.pas' {FORM_SELECIONA_RESPONSAVEL},
  Unit_TELA_PRINCIPAL in 'Unit_TELA_PRINCIPAL.pas' {Form_TELA_PRINCIPAL},
  Unit_TRATAMENTOS in 'Unit_TRATAMENTOS.pas' {Form_TRATAMENTOS},
  Unit_USUARIOS in 'Unit_USUARIOS.pas' {Form_USUARIO},
  Unit1 in 'Unit1.pas' {FORM_NOVO},
  TELA_CARREGAMENTO in 'TELA_CARREGAMENTO.pas' {Splash_Screen},
  UNIT_LIXO in 'UNIT_LIXO.pas' {RECUPERA_SENHA},
  Unit_BACKUP_TESTE in 'Unit_BACKUP_TESTE.pas' {Backup_TESTE};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TSplash_Screen, Splash_Screen);
  Application.CreateForm(TForm_RESPONSAVEL, Form_RESPONSAVEL);
  Application.CreateForm(TRECUPERA_SENHA, RECUPERA_SENHA);
  Application.CreateForm(TFORM_GRAVA_PAGAMENTO_PARCELADO, FORM_GRAVA_PAGAMENTO_PARCELADO);
  Application.CreateForm(TForm1, Form1);
  Application.CreateForm(TFORM_NOVO, FORM_NOVO);
  Application.CreateForm(TFORM_CAIXA, FORM_CAIXA);
  Application.CreateForm(TForm_CONS_AGENDAMENTO, Form_CONS_AGENDAMENTO);
  Application.CreateForm(TForm_CONS_PAGAM_APRAZO, Form_CONS_PAGAM_APRAZO);
  Application.CreateForm(TForm_CONS_PAGAM_AVISTA, Form_CONS_PAGAM_AVISTA);
  Application.CreateForm(TForm_CONS_PAGAM_PARCELADO, Form_CONS_PAGAM_PARCELADO);
  Application.CreateForm(TFORM_CONSULTA_ALTERA_DENTISTA, FORM_CONSULTA_ALTERA_DENTISTA);
  Application.CreateForm(TFORM_CONSULTA_ALTERA_TRATAMENTO, FORM_CONSULTA_ALTERA_TRATAMENTO);
  Application.CreateForm(TForm_CONSULTA_DENTISTA, Form_CONSULTA_DENTISTA);
  Application.CreateForm(TForm_DESPESAS, Form_DESPESAS);
  Application.CreateForm(TFORM_ERRO, FORM_ERRO);
  Application.CreateForm(TForm_ESCOLHE_PAGAMENTO, Form_ESCOLHE_PAGAMENTO);
  Application.CreateForm(TForm_FUNCIONARIOS, Form_FUNCIONARIOS);
  Application.CreateForm(TFORM_GRAVA_AGENDAMENTO, FORM_GRAVA_AGENDAMENTO);
  Application.CreateForm(TFORM_GRAVA_CONSULTA, FORM_GRAVA_CONSULTA);
  Application.CreateForm(TFORM_GRAVA_DENTISTA, FORM_GRAVA_DENTISTA);
  Application.CreateForm(TFORM_GRAVA_FINANCAS, FORM_GRAVA_FINANCAS);
  Application.CreateForm(TFORM_GRAVA_FUNCIONARIO, FORM_GRAVA_FUNCIONARIO);
  Application.CreateForm(TFORM_GRAVA_PACIENTE, FORM_GRAVA_PACIENTE);
  Application.CreateForm(TFORM_GRAVA_PAGAMENTO_DENTISTA, FORM_GRAVA_PAGAMENTO_DENTISTA);
  Application.CreateForm(TFORM_GRAVA_PAGAMENTO_FUNCIONARIO, FORM_GRAVA_PAGAMENTO_FUNCIONARIO);
  Application.CreateForm(TFORM_GRAVA_PAGAMENTO_APRAZO, FORM_GRAVA_PAGAMENTO_APRAZO);
  Application.CreateForm(TFORM_GRAVA_PAGAMENTO_AVISTA, FORM_GRAVA_PAGAMENTO_AVISTA);
  Application.CreateForm(TFORM_GRAVA_RESPONSAVEL, FORM_GRAVA_RESPONSAVEL);
  Application.CreateForm(TFORM_GRAVA_TRATAMENTO, FORM_GRAVA_TRATAMENTO);
  Application.CreateForm(TFORM_GRAVA_USUARIO, FORM_GRAVA_USUARIO);
  Application.CreateForm(TFORM_LOG, FORM_LOG);
  Application.CreateForm(TForm_MARCA_CONSULTA, Form_MARCA_CONSULTA);
  Application.CreateForm(TForm_PACIENTE, Form_PACIENTE);
  Application.CreateForm(TFORM_PAGAMENTO_DENTISTA, FORM_PAGAMENTO_DENTISTA);
  Application.CreateForm(TForm_PAG_FUNCIONARIO, Form_PAG_FUNCIONARIO);
  Application.CreateForm(TForm_PRODUTOS, Form_PRODUTOS);
  Application.CreateForm(TFORM_RECUPERA_SENHA, FORM_RECUPERA_SENHA);
  Application.CreateForm(TFORM_SELECIONA_AGENDAMENTO, FORM_SELECIONA_AGENDAMENTO);
  Application.CreateForm(TFORM_SELECIONA_RESPONSAVEL, FORM_SELECIONA_RESPONSAVEL);
  Application.CreateForm(TForm_TELA_PRINCIPAL, Form_TELA_PRINCIPAL);
  Application.CreateForm(TForm_TRATAMENTOS, Form_TRATAMENTOS);
  Application.CreateForm(TForm_USUARIO, Form_USUARIO);
  Application.CreateForm(TFORM_NOVO, FORM_NOVO);
  Application.CreateForm(TRECUPERA_SENHA, RECUPERA_SENHA);
  Application.CreateForm(TBackup_TESTE, Backup_TESTE);
  Application.Run;
end.
