-- CREATE DATABASE TCC
-- DROP DATABASE TCC

-- CRIE O BANCO DE DADOS CIDADE_ESTADO PRIMEIRO
-- APENAS APERTE "F5"

USE TCC
GO

ALTER AUTHORIZATION ON DATABASE :: TCC TO SA
GO

CREATE TABLE TB_RESPONSAVEL
(
	COD_RESPONSAVEL					INT IDENTITY PRIMARY KEY,
	NOME_RESPONSAVEL	  			VARCHAR(50) NOT NULL,
	RG_RESPONSAVEL					VARCHAR(13) NOT NULL,
	CPF_RESPONSAVEL					CHAR (15) NOT NULL, 
	SEXO_RESPONSAVEL				CHAR NOT NULL,
	TEL_RESPONSAVEL					VARCHAR(15) NOT NULL,
	ENDERECO_RESPONSAVEL			VARCHAR(100) NOT NULL,
	EMAIL_RESPONSAVEL				VARCHAR(30),
	CIDADE_RESPONSAVEL				INT FOREIGN KEY REFERENCES TB_CIDADE(CD_CIDADE) NOT NULL,
	NASCIMENTO_RESPONSAVEL			DATE NOT NULL,
	STATUS_RESPONSAVEL				BIT NOT NULL,
	DTHORACADASTRO_RESPONSAVEL		DATETIME NOT NULL
)

GO

CREATE TABLE TB_PACIENTE
(
	COD_PACIENTE			INT IDENTITY PRIMARY KEY,
	NOME_PACIENTE			VARCHAR(50) NOT NULL,
	RG_PACIENTE				VARCHAR(13) NULL,
	CPF_PACIENTE			CHAR (15) NULL, 
	SEXO_PACIENTE			CHAR NOT NULL,
	NASCIMENTO_PACIENTE		DATE NOT NULL,
	ENDERECO_PACIENTE		VARCHAR(100) NOT NULL,
	EMAIL_PACIENTE			VARCHAR(30),
	CIDADE_PACIENTE			INT FOREIGN KEY REFERENCES TB_CIDADE(CD_CIDADE) NOT NULL,
	TEL1_PACIENTE			VARCHAR(15) NOT NULL,
	TEL2_PACIENTE	  		VARCHAR(15) NULL,
	MENORDE18ANOS			BIT NOT NULL,
	RESPONSAVEL_PACIENTE	INT FOREIGN KEY REFERENCES TB_RESPONSAVEL(COD_RESPONSAVEL),
	OBS_PACIENTE			TEXT NULL,
	STATUS_PACIENTE			BIT NOT NULL,
	DTHORACADASTRO_PACIENTE	DATETIME NOT NULL
)

GO

CREATE TABLE TB_DENTISTA
(
	COD_DENTISTA			 INT IDENTITY PRIMARY KEY,
	NOME_DENTISTA			 VARCHAR(50) NOT NULL,
	SEXO_DENTISTA			 CHAR NOT NULL,
	CRO_DENTISTA			 VARCHAR(6) NOT NULL,
	EMAIL_DENTISTA			 VARCHAR(30),
	STATUS_DENTISTA			 CHAR NOT NULL,
	DTHORACADASTRO_DENTISTA  DATETIME NOT NULL
)

GO

CREATE TABLE TB_FUNCIONARIO
(
	COD_FUNCIONARIO				INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_FUNCIONARIO			VARCHAR(50) NOT NULL,
	SEXO_FUNCIONARIO			CHAR NOT NULL,
	NASCIMENTO_FUNCIONARIO		DATE NOT NULL,
	RG_FUNCIONARIO				VARCHAR(13) NOT NULL,
	CPF_FUNCIONARIO				CHAR(15) NOT NULL,
	ENDERECO_FUNCIONARIO		VARCHAR(50) NOT NULL,
	EMAIL_FUNCIONARIO			VARCHAR(30),
	CIDADE_FUNCIONÁRIO			INT FOREIGN KEY REFERENCES TB_CIDADE(CD_CIDADE) NOT NULL,
	TEL1_FUNCIONARIO			VARCHAR(15) NOT NULL,
	TEL2_FUNCIONARIO			VARCHAR(15) NULL,
	STATUS_FUNCIONARIO			BIT NOT NULL,
	DTHORACADASTRO_FUNCIONARIO  DATETIME NOT NULL
)

GO

CREATE TABLE TB_USUARIO	
(
	COD_USUARIO				 INT IDENTITY PRIMARY KEY,
	NOME_USUARIO			 VARCHAR(50) NOT NULL,
	LOGIN_USUARIO			 VARCHAR(15) NOT NULL,
	SENHA_USUARIO			 VARCHAR(10) NOT NULL,
	FUNCIONARIO_USUARIO		 INT FOREIGN KEY REFERENCES TB_FUNCIONARIO(COD_FUNCIONARIO) NULL,
	DENTISTA_USUARIO		 INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NULL,
	TIPO_USUARIO			 BIT NOT NULL,
	STATUS_USUARIO			 BIT NOT NULL,
	DTHORACADASTRO_USUARIO   DATETIME NOT NULL
)

GO

CREATE TABLE TB_LOG
(
	COD_LOG					INT IDENTITY PRIMARY KEY,
	DESCRICAO_LOG			VARCHAR(250) , 
	USUARIO_LOG				INT FOREIGN KEY REFERENCES TB_USUARIO(COD_USUARIO),
	DTHORA_LOG				DATETIME NOT NULL
)

GO

CREATE TABLE TB_PRODUTO
(
	COD_PRODUTO				INT IDENTITY PRIMARY KEY,
	NOME_PRODUTO			VARCHAR(15) NOT NULL,
	DENTISTA_PRODUTO		INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NULL,
	PRECOUNITARIO_PRODUTO	MONEY NOT NULL,
	TIPO_PRODUTO			VARCHAR(15) NOT NULL,
	VALIDADE_PRODUTO		DATE NULL,
	DATAPAGAMENTO_PRODUTO	DATE NOT NULL,
	QUANTIA_PRODUTO			INT NOT NULL,
	TOTAL_PRODUTO			MONEY NOT NULL,
	DTHORACADASTRO_PRODUTO  DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_DENTISTA -- MUDAR NOME DO CAMPO PARA COD_DENTISTA
(
	COD_PAGAMENTO				INT IDENTITY PRIMARY KEY,
	COD_DENTISTA				INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	VALOR_PAGAMENTO				MONEY NOT NULL,
	DATA_PAGAMENTO				DATE NOT NULL,
	STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_PAGAMENTO	DATETIME NOT NULL	
)

GO

CREATE TABLE TB_PAGAMENTO_FUNCIONARIO
(
	COD_PAGAMENTO				 INT IDENTITY PRIMARY KEY NOT NULL,
	COD_FUNCIONARIO_PAGAMENTO	 INT FOREIGN KEY REFERENCES TB_FUNCIONARIO(COD_FUNCIONARIO) NOT NULL,	
	VALORFIXO_PAGAMENTO			 MONEY NOT NULL,
	VALOREXTRA_PAGAMENTO		 MONEY NULL,
	TOTAL_PAGAMENTO				 MONEY NOT NULL,
	DATA_PAGAMENTO				 DATE NOT NULL,
	STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_PAGAMENTO	 DATETIME NOT NULL
)

GO

CREATE TABLE TB_DESPESA		
(	
	COD_DESPESA				INT IDENTITY PRIMARY KEY,
	TIPO_DESPESA			VARCHAR(20),
	PRODUTO_DESPESA			INT FOREIGN KEY REFERENCES TB_PRODUTO(COD_PRODUTO) NULL,
	PAG_FUNCIONARIO			INT FOREIGN KEY REFERENCES TB_PAGAMENTO_FUNCIONARIO(COD_PAGAMENTO) NULL,
	PAG_DENTISTA			INT FOREIGN KEY REFERENCES TB_PAGAMENTO_DENTISTA(COD_PAGAMENTO) NULL,
	VALOR_DESPESA			MONEY NOT NULL,
	DATAPAGAMENTO_DESPESA	DATE NOT NULL,
	OBS_DESPESA				TEXT NULL,
	DTHORACADASTRO_DESPESA  DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_PACIENTE_AVISTA
(
	COD_AVISTA					INT IDENTITY PRIMARY KEY,
	PACIENTE_AVISTA				INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_AVISTA				INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	VALOR_AVISTA				MONEY NOT NULL,
	DATAPAGAMENTO_AVISTA		DATE NOT NULL,
	TIPO_AVISTA					VARCHAR(15) NOT NULL,
		STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_AVISTA       DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_PACIENTE_APRAZO
(
	COD_APRAZO					INT IDENTITY PRIMARY KEY,
	PACIENTE_APRAZO				INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_APRAZO				INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	VALOR_APRAZO				MONEY NOT NULL,
	DATAPAGAMENTO_APRAZO		DATE NOT NULL, -- ESSA TABELA NAO TEM STATUS ENTAO TEM QUE REPENSAR
	TIPO_APRAZO					VARCHAR(15) NOT NULL,
	OBS_APRAZO					TEXT, 
	STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_APRAZO       DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_PACIENTE_PARCELADO
(
	COD_PARCELAMENTO			INT IDENTITY PRIMARY KEY NOT NULL,
	PACIENTE_PARCELAMENTO		INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_PARCELAMENTO		INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	TIPO_PARCELAMENTO			VARCHAR(15) NOT NULL, -- SE É CARTÃO, CARNÊN OU OUTRO
	VALOR_TOTAL					MONEY NOT NULL,
	QUANTIA_PARCELAS			INT NOT NULL,
	OBS_PARCELAMENTO			TEXT, ------------------------------
	DTHORACADASTRO_PARCELADO	DATETIME NOT NULL
)

GO

CREATE TABLE TB_PARCELA
(
	COD_PARCELA					INT IDENTITY PRIMARY KEY,
	COD_PARCELAMENTO			INT FOREIGN KEY REFERENCES TB_PAGAMENTO_PACIENTE_PARCELADO(COD_PARCELAMENTO) NOT NULL,
	DATAPAGAMENTO_PARCELA		DATE NULL,
	DATAVENCIMENTO_PARCELA		DATE NOT NULL,
	ENTRADA_PARCELA				BIT NULL,
	VALOR_PARCELA				MONEY NOT NULL, 
	DESCONTO_PARCELA			MONEY NULL,
	STATUS_PARCELA				BIT NOT NULL,
	OBS_PARCELA 				TEXT , 
	DTHORACADASTRO_PARCELA      DATETIME NOT NULL	
)

GO 

CREATE TABLE TB_TRATAMENTO
(
	COD_TRATAMENTO				INT IDENTITY PRIMARY KEY,
	NOME_TRATAMENTO				VARCHAR(20) NOT NULL,
	OBS_TRATAMENTO				TEXT,
	STATUS_TRATAMENTO			BIT NOT NULL,
	DTHORACADASTRO_TRATAMENTO	DATETIME NOT NULL
)

GO

CREATE TABLE TB_AGENDAMENTO
(
	COD_AGENDAMENTO				  INT IDENTITY PRIMARY KEY,
	DATAHORA_AGENDAMENTO		  DATETIME NOT NULL,
	PACIENTE_AGENDAMENTO		  INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_AGENDAMENTO		  INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	TRATAMENTO_AGENDAMENTO		  INT FOREIGN KEY REFERENCES TB_TRATAMENTO(COD_TRATAMENTO) NOT NULL,
	CONSULTA_AGENDAMENTO		  BIT,
	OBS_AGENDAMENTO				  TEXT NULL,
	DTHORACADASTRO_AGENDAMENTO    DATETIME NOT NULL
) 

GO

CREATE TABLE TB_CONSULTA
(
	COD_CONSULTA				INT IDENTITY PRIMARY KEY,
	DATAHORA_CONSULTA			DATETIME NOT NULL,
	PACIENTE_CONSULTA			INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_CONSULTA			INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	TRATAMENTO_CONSULTA			INT FOREIGN KEY REFERENCES TB_TRATAMENTO(COD_TRATAMENTO) NOT NULL,
	PREAGENDAMENTO_CONSULTA		INT FOREIGN KEY REFERENCES TB_AGENDAMENTO(COD_AGENDAMENTO)NULL,	
	OBS_CONSULTA				TEXT NULL,
	DTHORACADASTRO_CONSULTA		DATETIME NOT NULL
)

GO

CREATE TABLE TB_CAIXA
(
	COD_CAIXA					INT IDENTITY PRIMARY KEY,
	ENTRADA_CAIXA				MONEY NOT NULL,
	SAIDA_CAIXA					MONEY NOT NULL,
	TOTAL_CAIXA					MONEY NOT NULL,
	DTCADASTRO_CAIXA			DATETIME NOT NULL,
	PAGAMENTOS_AVISTA_CAIXA		INT FOREIGN KEY REFERENCES TB_PAGAMENTO_PACIENTE_AVISTA(COD_AVISTA) NULL,
	PAGAMENTOS_APRAZO_CAIXA		INT FOREIGN KEY REFERENCES TB_PAGAMENTO_PACIENTE_APRAZO(COD_APRAZO) NULL,
	PAGAMENTOS_PARCELAS_CAIXA	INT FOREIGN KEY REFERENCES TB_PARCELA (COD_PARCELA) NULL,
	DESPESAS_CAIXA				INT FOREIGN KEY REFERENCES TB_DESPESA (COD_DESPESA) NULL
)	


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE GRAVA_CAIXA @ENTRADA MONEY, @SAIDA MONEY,  @TOTAL MONEY, @DT_CADASTRO DATE, @AVISTA INT, @APRAZO INT, @PARCELAS INT, @DESPESAS INT
AS
	BEGIN
	
		INSERT INTO TB_CAIXA
		VALUES(@ENTRADA, @SAIDA, @TOTAL, @DT_CADASTRO, @AVISTA, @APRAZO, @PARCELAS, @DESPESAS)
	
	END	

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_TRATAMENTO @NOME VARCHAR(20), @OBS TEXT, @STATUS	BIT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_TRATAMENTO
		VALUES (@NOME, @OBS, @STATUS, @DTHORA_CADASTRO)
		
		DECLARE @ULTIMO_TRAT INT;
		SET @ULTIMO_TRAT = SCOPE_IDENTITY()
		RETURN @ULTIMO_TRAT ; 
	END

GO

	EXEC GRAVA_TRATAMENTO 'ORTODONTIA', NULL, 1, '20180615 15:30:42'
	EXEC GRAVA_TRATAMENTO 'IMPLANTODONTIA', NULL, 1, '20181121 14:52:00'
	EXEC GRAVA_TRATAMENTO 'DENTÍSTICA', NULL,1, '20181121 14:52:00'
	EXEC GRAVA_TRATAMENTO 'PERIODONTIA', NULL, 1, '20181121 14:52:00'
	EXEC GRAVA_TRATAMENTO 'ENDODONTIA', NULL, 1, '20181121 14:52:00'

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_TRATAMENTO @CODIGO INT, @NOME VARCHAR(20), @OBS TEXT, @STATUS BIT
AS
    BEGIN
       UPDATE TB_TRATAMENTO
       SET NOME_TRATAMENTO = @NOME, OBS_TRATAMENTO = @OBS, STATUS_TRATAMENTO = @STATUS
       WHERE COD_TRATAMENTO = @CODIGO

	   	DECLARE @ULTIMO_TRAT INT;
		SET @ULTIMO_TRAT = SCOPE_IDENTITY()
		RETURN @ULTIMO_TRAT ; 
    END

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO 

CREATE PROCEDURE GRAVA_DENTISTA @NOME VARCHAR(50), @SEXO CHAR, @CRO VARCHAR(6), @EMAIL VARCHAR(30), @STATUS BIT, @DTHORACADASTRO_DENTISTA DATETIME
AS
	BEGIN
		INSERT INTO TB_DENTISTA
		VALUES(@NOME, @SEXO, @CRO, @EMAIL, @STATUS, @DTHORACADASTRO_DENTISTA)
	  
	    DECLARE @ULTIMO_DENT INT;
		SET @ULTIMO_DENT = SCOPE_IDENTITY()
		RETURN @ULTIMO_DENT ; 	
	END	

GO
	
	EXEC GRAVA_DENTISTA 'RENATA',  'F',  '144528',  'renata_dent@gmail.com', 1, '20180615 15:30:48'
GO
	EXEC GRAVA_DENTISTA 'GIULIANO', 'M', '654546', 'giuliano924@hotmail.com', 1, '20180615 15:40:28'
GO
	EXEC GRAVA_DENTISTA 'PATRÍCIA',  'F',  '123456',  NULL, 1, '20180615 15:30:48'
GO
	EXEC GRAVA_DENTISTA 'MAURÍLIO', 'M', '789735', 'maurilio__@hotmail.com', 0, '20180615 15:40:28'
GO
	EXEC GRAVA_DENTISTA 'CLARA',  'F',  '147285', NULL, 0, '20180615 15:30:48'
GO
	EXEC GRAVA_DENTISTA 'OSVALDO', 'M', '693258', NULL, 1, '20180615 15:40:28'
GO
	EXEC GRAVA_DENTISTA 'ANA MARIA',  'F', '258936',  'ana.maria152@outlook.com', 0, '20180615 15:30:48'
GO
	EXEC GRAVA_DENTISTA 'THALES', 'M', '713739', NULL, 1, '20180615 15:40:28'

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_DENTISTA @CODIGO INT,  @NOME VARCHAR(50), @SEXO CHAR, @CRO VARCHAR(6), @EMAIL VARCHAR(30), @STATUS BIT
AS
	BEGIN
	   UPDATE TB_DENTISTA
	   SET NOME_DENTISTA = @NOME, SEXO_DENTISTA = @SEXO, CRO_DENTISTA = @CRO, EMAIL_DENTISTA=@EMAIL, STATUS_DENTISTA = @STATUS
	   WHERE COD_DENTISTA = @CODIGO

	    DECLARE @ULTIMO_DENT INT;
		SET @ULTIMO_DENT = SCOPE_IDENTITY()
		RETURN @ULTIMO_DENT ; 	
	END

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO 

CREATE PROCEDURE GRAVA_RESPONSAVEL @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR(15), @SEXO CHAR, @TELEFONE VARCHAR(15), 
								   @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @NASCIMENTO DATE, @STATUS BIT, @DTHORA_CADASTRO DATETIME 
AS 
	BEGIN
		INSERT INTO TB_RESPONSAVEL
		VALUES (@NOME, @RG, @CPF, @SEXO, @TELEFONE, @ENDERECO, @EMAIL, @CIDADE, @NASCIMENTO, @STATUS, @DTHORA_CADASTRO)
		
		DECLARE @ULTIMO_R INT;
		SET @ULTIMO_R = SCOPE_IDENTITY()
		RETURN @ULTIMO_R ; 
	END

GO
	EXEC GRAVA_RESPONSAVEL 'BIANCA CARVALHO', '55.541.321-2',  '46693100899', 'F', '(14)33568-891',  'SITIO SÃO BERNARDO' , NULL, 8886, '1995-09-14', 1, '20180621 11:01:20.000'
GO 
	EXEC GRAVA_RESPONSAVEL 'CARLOS VARRASCHIN', '22.321.008-3', '28835324631', 'M', '(15)99837-2291', 'RUA SANTA CATARINA, 223', 'carlosvarraschin@outlook.com', 1813, '1997-02-10', 1, '20181121 13:20:12'
GO 
	EXEC GRAVA_RESPONSAVEL 'LORENA ELIANE EMILY ARAÚJO', '32.855.963-5', '16956692074', 'F', '(15)99874-1281', 'RUA VICENTE FERREIRA, 182', NULL, 1813, '1993-01-31', 0, '20181121 13:20:12'
GO 
	EXEC GRAVA_RESPONSAVEL 'MARCOS VINICIUS CAIO CAVALCANTI', '39.318.482-1', '77897287840', 'M', '(14)99740-3297', 'RUA HIROSI NABESIMA, 776', NULL, 1813, '1980-06-01', 1, '20181121 13:20:12'
GO 
	EXEC GRAVA_RESPONSAVEL 'LUZIA ELISA JESUS', '37.911.051-9', '71323712828', 'F', '(14)99297-7067', 'RUA DONA ISAURA, 437', 'luziaelisajesus_@gmail.com', 1813, '1995-10-18', 1, '20181121 13:20:12'
GO 
	EXEC GRAVA_RESPONSAVEL 'OTÁVIO MÁRIO OLIVER BAPTISTA', '17.783.384-1', '29364536827', 'M', '(15)99865-5191', 'RUA FRANCISCA RODDRIGUES ADRIANO, 204', 'otaviomarioliver1205@hotmail.com', 1813, '1989-12-05', 1, '20181121 13:20:12'

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GO

CREATE PROCEDURE ALTERA_RESPONSAVEL @CODIGO INT, @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR(15), @SEXO CHAR, @TELEFONE VARCHAR(15), 
								   @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @NASCIMENTO DATE, @STATUS BIT
AS 
	BEGIN
	   UPDATE TB_RESPONSAVEL
	   SET NOME_RESPONSAVEL = @NOME, RG_RESPONSAVEL = @RG, CPF_RESPONSAVEL = @CPF, SEXO_RESPONSAVEL = @SEXO, 
	       TEL_RESPONSAVEL = @TELEFONE,ENDERECO_RESPONSAVEL = @ENDERECO, EMAIL_RESPONSAVEL = @EMAIL, CIDADE_RESPONSAVEL= @CIDADE, 
	       NASCIMENTO_RESPONSAVEL = @NASCIMENTO, STATUS_RESPONSAVEL = @STATUS
	   WHERE COD_RESPONSAVEL = @CODIGO

		DECLARE @ULTIMO_R INT;
		SET @ULTIMO_R = SCOPE_IDENTITY()
		RETURN @ULTIMO_R ; 
	END    

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO -----------STATUSSS-------------------------

CREATE PROCEDURE GRAVA_PAGAMENTO_DENTISTA @CODIGO_DENTISTA INT, @VALOR MONEY, @DATA_PAGAMENTO DATE, @STATUS BIT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_DENTISTA
		VALUES(@CODIGO_DENTISTA, @VALOR, @DATA_PAGAMENTO, @STATUS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_PAG INT;
		SET @ULTIMO_PAG = SCOPE_IDENTITY()
		RETURN @ULTIMO_PAG ; 
	END

GO
	EXEC GRAVA_PAGAMENTO_DENTISTA 5, 1250, '2018-08-31', 1, '20181128 01:31:26'
GO
	EXEC GRAVA_PAGAMENTO_DENTISTA 1, 1135.54, '2018-10-31', 1, '20181128 01:31:27'
GO
	EXEC GRAVA_PAGAMENTO_DENTISTA 3, 1045.55, '2018-11-30', 0, '20181128 01:31:28'
GO
	EXEC GRAVA_PAGAMENTO_DENTISTA 6, 1005.67, '2018-09-29', 1, '20181128 01:31:29'
GO
	EXEC GRAVA_PAGAMENTO_DENTISTA 2, 1347, '2018-12-31', 0, '20181128 01:31:30'
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GO 

CREATE PROCEDURE GRAVA_FUNCIONARIO @NOME VARCHAR(50), @SEXO CHAR, @NASCIMENTO DATE, @RG VARCHAR(13), 
								   @CPF CHAR (15), @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, 
								   @TELEFONE VARCHAR(15), @TELEFONE2 VARCHAR(15), @STATUS BIT, @DTHORA_CADASTRO DATETIME
AS 
	BEGIN
		INSERT INTO TB_FUNCIONARIO
		VALUES (@NOME, @SEXO, @NASCIMENTO, @RG, @CPF, @ENDERECO, @EMAIL, @CIDADE, @TELEFONE, @TELEFONE2, @STATUS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_F INT;
		SET @ULTIMO_F = SCOPE_IDENTITY()
		RETURN @ULTIMO_F ; 
	END 

GO 
	EXEC GRAVA_FUNCIONARIO 'MICHELE', 'F', '1997-09-19', '12.223.993-X', '39902811899', 'RUA AUGUSTA, 234', 'mi.chele97@gmail.com', 8886, '(00)00000-0000', '(00)00000-0000', 1, '20181027 22:48:20'
GO 
	EXEC GRAVA_FUNCIONARIO 'FRANCISCO', 'M', '1997-01-22', '13.234.443-D', '89347589993', 'RUA PAULISTA, 234', 'francisco_0101@hotmail.com', 8886, '(00)00000-0000', '(00)00000-0000', 0, '20181027 22:48:56'
GO 
	EXEC GRAVA_FUNCIONARIO 'AMANDA', 'F', '1990-05-27', '45.567.182-5', '65866651831', 'RUA SANTA CLARA, 500', 'amanda52790@outlook.com', 8886, '(00)00000-0000', '(00)00000-0000', 1, '20181027 22:48:20'
GO 
	EXEC GRAVA_FUNCIONARIO 'PEDRO', 'M', '1989-11-03', '13.234.443-D', '89347589993', 'RUA PAULISTA, 234', 'pedro1065__@hotmail.com', 8886, '(00)00000-0000', '(00)00000-0000', 1, '20181027 22:48:56'

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_FUNCIONARIO @CODIGO INT, @NOME VARCHAR(50), @SEXO CHAR, @NASCIMENTO DATE, @RG VARCHAR(13), 
								   @CPF CHAR (15), @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, 
								   @TELEFONE VARCHAR(15), @TELEFONE2 VARCHAR(15), @STATUS BIT
AS
    BEGIN
       UPDATE TB_FUNCIONARIO
       SET NOME_FUNCIONARIO = @NOME, SEXO_FUNCIONARIO = @SEXO, NASCIMENTO_FUNCIONARIO = @NASCIMENTO, RG_FUNCIONARIO = @RG,
           CPF_FUNCIONARIO = @CPF, ENDERECO_FUNCIONARIO = @ENDERECO, EMAIL_FUNCIONARIO = @EMAIL, CIDADE_FUNCIONÁRIO = @CIDADE,
           TEL1_FUNCIONARIO = @TELEFONE, TEL2_FUNCIONARIO = @TELEFONE2, STATUS_FUNCIONARIO = @STATUS
       WHERE COD_FUNCIONARIO = @CODIGO
	   	
		DECLARE @ULTIMO_F INT;
		SET @ULTIMO_F = SCOPE_IDENTITY()
		RETURN @ULTIMO_F ; 
    END	
	  

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PACIENTE @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR (15), @SEXO CHAR, @NASCIMENTO DATE,  
								@ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @TELEFONE VARCHAR(15), 
								@TELEFONE2 VARCHAR(15), @MENOR_DE_18 BIT, @RESPONSAVEL INT, @OBS TEXT, @STATUS BIT, 
								@DTHORA_CADASTRO datetime
AS
	BEGIN
		INSERT INTO TB_PACIENTE 
		VALUES(@NOME, @RG, @CPF, @SEXO, @NASCIMENTO, @ENDERECO, @EMAIL, @CIDADE, @TELEFONE, @TELEFONE2, @MENOR_DE_18, 
			   @RESPONSAVEL, @OBS, @STATUS, @DTHORA_CADASTRO)
			   
		DECLARE @ULTIMO_PACIENTE INT;
		SET @ULTIMO_PACIENTE = SCOPE_IDENTITY()
		RETURN @ULTIMO_PACIENTE ;
	END 
	SELECT * FROM TB_PACIENTE
GO

	EXEC GRAVA_PACIENTE 'MARIANA ANDRADE', '16.388.047-5', '43903201065', 'F', '2001-09-22', 'SITIO SÃO BERNARDO', NULL, 8614, '(14)99955-6661' , NULL, 0, NULL, NULL, 1, '20181121 14:46:51'
GO
	EXEC GRAVA_PACIENTE 'ALICE MARIA RODRIGUES', '46.765.267-3', '07530454005', 'F', '1993-03-11', 'RUA ÁGATA, 142', NULL, 8614, '(14)99889-3056' , NULL, 0, NULL, NULL, 1, '20180628 11:36:34'
GO 
	EXEC GRAVA_PACIENTE 'VICTÓRIA MARTINS', '12.178.458-7', '99886527048', 'F', '1980-02-07', 'RUA SANTO ANTONIO, 138', NULL, 1813, '(14)99889-3056', '(14)99889-3056', 0, NULL, NULL, 0,  '20181121 14:46:51'   
GO
	EXEC GRAVA_PACIENTE 'ELIAS FERNANDO', '36.202.962-3', '17272375019', 'M', '1995-04-16', 'RUA ÁGATA, 142', NULL, 8614, '(14)99889-3056', NULL, 0, NULL, NULL, 1,  '20180628 11:36:34'   
GO 
	EXEC GRAVA_PACIENTE 'LUNA YASMIN DA MOTA', '43.125.354-7', '13675943836', 'F', '2003-01-26', 'RUA CAPITÃO SEBASTIÃO DE ALMEIDA SOBRINHO, 918', NULL, 8614, '(14)99821-3480', NULL, 1, 3, NULL, 1,  '20181121 14:46:51'   
GO
	EXEC GRAVA_PACIENTE 'THOMAS BRYAN MONTEIRO', '24.130.453-2', '61530597838', 'M', '2000-05-28', 'ALAMEDA TIMBAÚBA, 494', NULL, 1813, '(14)99675-9556', '(14)99745-3846', 0, NULL, NULL, 0,  '20181121 14:46:51'   
GO 
	EXEC GRAVA_PACIENTE 'RAQUEL AMANDA CASTRO', '31.380.293-2', '605463098-95', 'F', '1999-12-26', 'RUA JOAQUIM DE TOLEDO, 589', NULL, 8614, '(15)99871-9607', '(15)99657-6755', 0, NULL, NULL, 1,  '20180628 11:36:34'   
GO
	EXEC GRAVA_PACIENTE 'MANUEL AUGUSTO PEIXOTO', '22.037.601-3', '15332766840', 'M', '1994-06-30', 'RUA YOSIKO AKAMINE, 522', 'manuelaugustothomaspeixoto_@gmail.com', 1813, '(14)99607-0899', '(14)99785-3625', 0, NULL, NULL, 1,  '20180628 11:36:34'   
GO 
	EXEC GRAVA_PACIENTE 'FABIANA PATRÍCIA ELAINE', '15.079.449-6', '30763854883', 'F', '1980-07-14', 'RUA VALORBE, 327', NULL, 8614, '(14)99207-9433', NULL, 0, NULL, NULL, 0,  '20181121 14:46:51'   
GO
	EXEC GRAVA_PACIENTE 'VICTOR PEDRO DA CRUZ', '25.439.486-3', '99920856819', 'M', '2004-10-31', 'AVENIDA DOUTOR AMIN SIMÃO, 815', NULL, 1813, '(15)99780-4284', NULL, 1, 1, NULL, 0,  '20180628 11:36:34'   

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PACIENTE @CODIGO INT, @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR (15), @SEXO CHAR, @NASCIMENTO DATE,  
								@ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @TELEFONE VARCHAR(15), 
								@TELEFONE2 VARCHAR(15), @MENOR_DE_18 BIT, @RESPONSAVEL INT, @OBS TEXT, @STATUS BIT
AS
	BEGIN

	  UPDATE TB_PACIENTE
	  SET NOME_PACIENTE = @NOME, RG_PACIENTE = @RG, CPF_PACIENTE = @CPF, SEXO_PACIENTE = @SEXO, 
	      NASCIMENTO_PACIENTE = @NASCIMENTO,ENDERECO_PACIENTE = @ENDERECO, EMAIL_PACIENTE = @EMAIL, 
	      CIDADE_PACIENTE = @CIDADE, TEL1_PACIENTE = @TELEFONE, TEL2_PACIENTE = @TELEFONE2, 
	      MENORDE18ANOS = @MENOR_DE_18, RESPONSAVEL_PACIENTE = @RESPONSAVEL, OBS_PACIENTE = @OBS, 
	      STATUS_PACIENTE = @STATUS
      WHERE COD_PACIENTE = @CODIGO
      
      	DECLARE @ULTIMO_PACIENTE INT;
		SET @ULTIMO_PACIENTE = SCOPE_IDENTITY()
		RETURN @ULTIMO_PACIENTE ;

    END 	
    				
--------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_USUARIO @NOME VARCHAR(50), @LOGIN VARCHAR(15), @SENHA VARCHAR(10), 
							   @FUNCIONARIO INT, @DENTISTA INT, @TIPO BIT, @STATUS BIT, 
							   @DTHR_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_USUARIO 
		VALUES (@NOME, @LOGIN, @SENHA, @FUNCIONARIO, @DENTISTA, @TIPO, @STATUS, @DTHR_CADASTRO)
		DECLARE @ULTIMO_U INT;
		SET @ULTIMO_U = SCOPE_IDENTITY()
		RETURN @ULTIMO_U ;
	END

GO 

	EXEC GRAVA_USUARIO 'U_FÁBRICA', 'ADMIN', 'ADMIN', NULL, 1, 1, 1, '20180628 11:36:34'
GO
	EXEC GRAVA_USUARIO 'U_FÁBRICA', 'COMUM', 'COMUM', 2, NULL, 0, 1, '20180628 11:36:34'
GO
	EXEC GRAVA_USUARIO 'MICHELE', 'MI', 'MI', 1, NULL, 1, 1, '20180628 11:36:34'
GO
	EXEC GRAVA_USUARIO 'AMANDA', 'AMANDINHA', '4321AMANDA', 3, NULL, 0, 0, '20180628 11:36:34'

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_USUARIO @CODIGO INT,@NOME VARCHAR(50), @LOGIN VARCHAR(15), @SENHA VARCHAR(10), 
							   @FUNCIONARIO INT, @DENTISTA INT, @TIPO BIT, @STATUS BIT
AS
	BEGIN
	   UPDATE TB_USUARIO
	   SET NOME_USUARIO = @NOME, LOGIN_USUARIO = @LOGIN, SENHA_USUARIO = @SENHA, FUNCIONARIO_USUARIO=@FUNCIONARIO, DENTISTA_USUARIO=@DENTISTA,
	       TIPO_USUARIO = @TIPO, STATUS_USUARIO = @STATUS
	   WHERE COD_USUARIO = @CODIGO
	END
		 	
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE GRAVA_AGENDAMENTO @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, 
								   @CONSULTA BIT, @OBS TEXT, @DTHORA_CADASTRO DATETIME
AS	
	BEGIN
		INSERT INTO TB_AGENDAMENTO
		VALUES (@DATAHORA, @PACIENTE, @DENTISTA, @TRATAMENTO, @CONSULTA, @OBS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_AG INT;
		SET @ULTIMO_AG = SCOPE_IDENTITY()
		RETURN @ULTIMO_AG ;
	END

GO	
	EXEC GRAVA_AGENDAMENTO  '20181213 12:00:00', 1, 6, 5, 0, NULL, '20180627 17:33:24'
GO	
	EXEC GRAVA_AGENDAMENTO  '20181030 09:30:00', 2, 4, 3, 0, NULL, '20180627 17:33:24'
GO	
	EXEC GRAVA_AGENDAMENTO  '20190913 14:30:00', 6, 5, 1, 1, NULL, '20180627 17:33:24'
GO	
	EXEC GRAVA_AGENDAMENTO  '20181213 12:00:00', 3, 2, 4, 0, NULL, '20180627 17:33:24'

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_CONSULTA @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, 
								@PREAGENDADO INT, @OBS TEXT, @DTHORA_CADASTRO DATETIME
AS 
	BEGIN
		INSERT INTO TB_CONSULTA
		VALUES (@DATAHORA, @PACIENTE, @DENTISTA, @TRATAMENTO, @PREAGENDADO, @OBS, @DTHORA_CADASTRO)
		DECLARE @ULTIMA_CONS INT;
		SET @ULTIMA_CONS = SCOPE_IDENTITY()
		RETURN @ULTIMA_CONS ;
	END

GO
	EXEC GRAVA_CONSULTA '20190913 14:30:00', 6, 5, 5, 3, NULL, '20181121 14:50:00'
GO
	EXEC GRAVA_CONSULTA '20181024 09:30:00', 1, 8, 2, NULL, NULL, '20181121 14:50:00'
GO
	EXEC GRAVA_CONSULTA '20181104 15:14:28', 5, 3, 4, NULL, NULL, '20181121 14:50:00'
GO
	EXEC GRAVA_CONSULTA '20181217 08:03:57', 3, 4, 1, NULL, NULL, '20181121 14:50:00'
GO
	EXEC GRAVA_CONSULTA '20181130 10:44:08', 2, 7, 3, NULL, NULL, '20181121 14:50:00'

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE GRAVA_PRODUTO @NOME VARCHAR(15), @DENTISTA INT, @PRECO_UNITARIO MONEY, @TIPO VARCHAR(15), @VALIDADE DATE, 
							   @DATA_PAGAMENTO DATE, @QUANTIA INT, @TOTAL MONEY, @DTHORACADASTRO_PRODUTO DATETIME

AS
	BEGIN
		INSERT INTO TB_PRODUTO
		VALUES (@NOME, @DENTISTA, @PRECO_UNITARIO, @TIPO, @VALIDADE, @DATA_PAGAMENTO, @QUANTIA, @TOTAL, @DTHORACADASTRO_PRODUTO)
		
		DECLARE @ULTIMO_COD_PRODUTO INT;
		SET @ULTIMO_COD_PRODUTO = SCOPE_IDENTITY()
		RETURN @ULTIMO_COD_PRODUTO ;
	END
	
GO
	EXEC GRAVA_PRODUTO 'PINÇA', 2, 12.5, 'INSTRUMENTO', NULL, '2018-11-28', 15, 187.5, '20181128 01:14:26'
GO
	EXEC GRAVA_PRODUTO 'PÓ DE CAFÉ', 2, 24.65, 'ALIMENTO', NULL, '2018-10-27', 3, 73.95, '20181128 01:14:45'
GO
	EXEC GRAVA_PRODUTO 'MÁSCARA', 2, 50.23, 'DESCARTÁVEIS', NULL, '2018-09-15', 2, 100.46, '20181128 01:14:57'
GO
	EXEC GRAVA_PRODUTO 'ESPELHO', 2, 20.21, 'INSTRUMENTO', NULL, '2018-12-08', 15, 303.15, '20181128 01:14:01'
GO
	EXEC GRAVA_PRODUTO 'BOLACHA', 2, 4.35, 'ALIMENTO', NULL, '2018-09-10', 3, 13.5, '20181128 01:14:13'
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PRODUTO @CODIGO INT, @NOME VARCHAR(15), @PRECO_UNITARIO MONEY, @TIPO VARCHAR(15), @DENTISTA INT, 
								@VALIDADE DATE, @QUANTIA INT, @DTHORACADASTRO DATETIME, @DATA_PAG DATE, @TOTAL MONEY
AS
	BEGIN
	   UPDATE TB_PRODUTO
	   SET NOME_PRODUTO = @NOME, DENTISTA_PRODUTO=@DENTISTA ,PRECOUNITARIO_PRODUTO = @PRECO_UNITARIO, TIPO_PRODUTO = @TIPO, 
		   VALIDADE_PRODUTO = @VALIDADE, DATAPAGAMENTO_PRODUTO=@DATA_PAG ,QUANTIA_PRODUTO = @QUANTIA, TOTAL_PRODUTO=@TOTAL ,DTHORACADASTRO_PRODUTO = @DTHORACADASTRO
	   WHERE COD_PRODUTO = @CODIGO
	END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_DESPESA @TIPO VARCHAR(15), @PRODUTO INT, @PAG_FUNC INT, @PAG_DENT INT, @VALOR MONEY, @DATAPAGAMENTO DATE, @OBS TEXT, @DTHORACADASTRO_DESPESA DATETIME
AS
	BEGIN
		INSERT INTO TB_DESPESA
		VALUES(@TIPO, @PRODUTO, @PAG_FUNC, @PAG_DENT, @VALOR, @DATAPAGAMENTO, @OBS, @DTHORACADASTRO_DESPESA)		
		DECLARE @ULTIMO_COD_DESPESA INT;
		SET @ULTIMO_COD_DESPESA = SCOPE_IDENTITY()
		RETURN @ULTIMO_COD_DESPESA ;
	END 

GO
	EXEC GRAVA_DESPESA 'ENERGIA', NULL, NULL, NULL, 110.45, '2018-10-12', NULL, '20181128 01:23:45'
GO
	EXEC GRAVA_DESPESA 'PRODUTO', 5, NULL, NULL, 110.45, '2018-10-12', NULL, '20181128 01:23:46'
GO
	EXEC GRAVA_DESPESA 'ÁGUA', NULL, NULL, NULL, 95.23, '2018-10-12', NULL, '20181128 01:23:47'
GO
	EXEC GRAVA_DESPESA 'PRODUTO', 2, NULL, NULL, 73.95, '2018-10-27', NULL, '20181128 01:23:48'
GO
	EXEC GRAVA_DESPESA 'PRODUTO', 4, NULL, NULL, 303.15, '2018-12-08', NULL, '20181128 01:23:49'
GO
	EXEC GRAVA_DESPESA 'ALUGUEL', NULL, NULL, NULL, 650, '2018-10-12', NULL, '20181128 01:23:50'
GO
	EXEC GRAVA_DESPESA 'PRODUTO', 1, NULL, NULL, 187.5, '2018-11-28', NULL, '20181128 01:23:51'
GO
	EXEC GRAVA_DESPESA 'PRODUTO', 3, NULL, NULL, 100.46, '2018-09-15', NULL, '20181128 01:23:52'

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_DESPESA @CODIGO INT, @TIPO VARCHAR(15), @VALOR MONEY, @DATAPAGAMENTO DATE, @OBS TEXT, @DTHORACADASTRO DATETIME
AS
	BEGIN
	   UPDATE TB_DESPESA
	   SET TIPO_DESPESA = @TIPO, VALOR_DESPESA = @VALOR, DATAPAGAMENTO_DESPESA = @DATAPAGAMENTO, 
	       OBS_DESPESA = @OBS, DTHORACADASTRO_DESPESA = @DTHORACADASTRO
	   WHERE COD_DESPESA = @CODIGO   	
	   	DECLARE @ULTIMO_COD_DESPESA INT;
		SET @ULTIMO_COD_DESPESA = SCOPE_IDENTITY()
		RETURN @ULTIMO_COD_DESPESA ;
	END
	

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PAGAMENTO_PACIENTE_AVISTA @PACIENTE INT, @DENTISTA INT, 
												 @VALOR MONEY, @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), @STATUS BIT,
												 @DTHORA_CADASTRO DATETIME
AS
	BEGIN
	
		INSERT INTO TB_PAGAMENTO_PACIENTE_AVISTA
		VALUES(@PACIENTE, @DENTISTA, @VALOR, @DATAPAGAMENTO, @TIPO, @STATUS, @DTHORA_CADASTRO)		
		DECLARE @ULTIMO_COD_AVISTA INT;
		SET @ULTIMO_COD_AVISTA = SCOPE_IDENTITY() -- funcionando
		RETURN @ULTIMO_COD_AVISTA ;
		
	END

GO
	EXEC GRAVA_PAGAMENTO_PACIENTE_AVISTA 6, 2, 83, '2018-11-25', 'DINHEIRO', 1, '20181128 01:38:12'
GO
	EXEC GRAVA_PAGAMENTO_PACIENTE_AVISTA 1, 7, 40.45, '2018-10-04', 'CHEQUE', 1, '20181128 01:38:13'
GO
	EXEC GRAVA_PAGAMENTO_PACIENTE_AVISTA 5, 3, 120, '2018-10-13', 'CARTÃO', 1, '20181128 01:38:14'
GO
	EXEC GRAVA_PAGAMENTO_PACIENTE_AVISTA 3, 8, 50.73, '2018-11-21', 'CARNÊ', 1, '20181128 01:38:15'
GO
	EXEC GRAVA_PAGAMENTO_PACIENTE_AVISTA 8, 1, 56.47, '2018-09-30', 'CHEQUE', 1, '20181128 01:38:16'

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

create PROCEDURE ALTERA_PAGAMENTO_PACIENTE_AVISTA @CODIGO INT, @PACIENTE INT, @DENTISTA INT, @VALOR MONEY, 
												  @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), @STATUS BIT
AS
	BEGIN
       UPDATE TB_PAGAMENTO_PACIENTE_AVISTA
       SET PACIENTE_AVISTA = @PACIENTE, DENTISTA_AVISTA = @DENTISTA, VALOR_AVISTA = @VALOR, 
	       DATAPAGAMENTO_AVISTA = @DATAPAGAMENTO, TIPO_AVISTA = @TIPO, STATUS_PAGAMENTO = @STATUS 
       WHERE COD_AVISTA = @CODIGO
	   DECLARE @ULTIMO_ALT_AVISTA INT;
	   SET @ULTIMO_ALT_AVISTA = SCOPE_IDENTITY() -- funcionando
	   RETURN @ULTIMO_ALT_AVISTA ;
    END


GO

CREATE PROCEDURE ALTERA_PAGAMENTO_PACIENTE_APRAZO @CODIGO INT, @PACIENTE INT, @DENTISTA INT, @VALOR MONEY, 
												  @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), @OBS TEXT, @STATUS BIT
AS
	BEGIN
       UPDATE TB_PAGAMENTO_PACIENTE_APRAZO
       SET PACIENTE_APRAZO = @PACIENTE, DENTISTA_APRAZO = @DENTISTA, VALOR_APRAZO = @VALOR, 
	       DATAPAGAMENTO_APRAZO = @DATAPAGAMENTO, TIPO_APRAZO = @TIPO, OBS_APRAZO = @OBS ,STATUS_PAGAMENTO = @STATUS 
       WHERE COD_APRAZO = @CODIGO
	   DECLARE @ULTIMO_ALT_AP INT;
	   SET @ULTIMO_ALT_AP = SCOPE_IDENTITY() 
	   RETURN @ULTIMO_ALT_AP ;
    END
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PAGAMENTO_PACIENTE_PARCELADO @PACIENTE INT, @DENTISTA INT, @TIPO VARCHAR(15), @VALOR_TOTAL MONEY, 
													@QUANTIA INT, @OBS TEXT, @DTHORA_CADASTRO DATETIME 
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_PACIENTE_PARCELADO
		VALUES(@PACIENTE, @DENTISTA, @TIPO, @VALOR_TOTAL, @QUANTIA, @OBS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_PARCELAMENTO INT
		SET @ULTIMO_PARCELAMENTO = SCOPE_IDENTITY()
		RETURN @ULTIMO_PARCELAMENTO

	END

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PARCELAS @COD_PARCELAMENTO INT, @DATAPAGAMENTO DATE, @DATAVENCIMENTO DATE, @ENTRADA BIT, @VALOR MONEY, @DESCONTO MONEY,
								@STATUS_PARCELA BIT, @OBS TEXT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PARCELA
		VALUES(@COD_PARCELAMENTO, @DATAPAGAMENTO, @DATAVENCIMENTO, @ENTRADA, @VALOR, @DESCONTO, @STATUS_PARCELA, @OBS, @DTHORA_CADASTRO)
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE GRAVA_PAGAMENTO_PACIENTE_APRAZO @PACIENTE INT, @DENTISTA INT, @VALOR MONEY, @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), 
												 @OBS TEXT, @STATUS BIT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_PACIENTE_APRAZO 
		VALUES (@PACIENTE, @DENTISTA, @VALOR, @DATAPAGAMENTO, @TIPO, @OBS, @STATUS ,@DATAPAGAMENTO)
		DECLARE @ULTIMO_AP INT
		SET @ULTIMO_AP = SCOPE_IDENTITY()
		RETURN @ULTIMO_AP
	END

GO
	EXEC GRAVA_PAGAMENTO_PACIENTE_APRAZO 9, 6, 80.5, '2018-12-15', 'CARNÊ', NULL, 0, '20181128 01:54:03'		
GO	
	EXEC GRAVA_PAGAMENTO_PACIENTE_APRAZO 7, 1, 125, '2018-10-15', 'CHEQUE', NULL, 1, '20181128 01:54:04'		
GO	
	EXEC GRAVA_PAGAMENTO_PACIENTE_APRAZO 5, 5, 75.50, '2018-11-30', 'CHEQUE', NULL, 1, '20181128 01:54:05'			
GO	
	EXEC GRAVA_PAGAMENTO_PACIENTE_APRAZO 1, 3, 100.75, '2018-09-15', 'DINHEIRO', NULL, 1, '20181128 01:54:06'			
GO	
	EXEC GRAVA_PAGAMENTO_PACIENTE_APRAZO 2, 8, 67.5, '2018-12-23', 'CARTÃO', NULL, 0, '20181128 01:54:07'	

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PAGAMENTO_FUNCIONARIO @COD_FUNCIONARIO INT, @VALOR_FIXO MONEY, @VALOR_EXTRA MONEY, @TOTAL MONEY, @DATA DATE, @STATUS BIT , @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_FUNCIONARIO
		VALUES(@COD_FUNCIONARIO, @VALOR_FIXO, @VALOR_EXTRA, @TOTAL, @DATA, @STATUS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_PF INT
		SET @ULTIMO_PF = SCOPE_IDENTITY()
		RETURN @ULTIMO_PF
	END

GO
	EXEC GRAVA_PAGAMENTO_FUNCIONARIO 2, 550.47, NULL, 550.47, '2018-11-30', 0, '20181128 02:01:11'
GO
	EXEC GRAVA_PAGAMENTO_FUNCIONARIO 1, 501, 50, 551, '2018-10-31', 0, '20181128 02:01:12'
GO
	EXEC GRAVA_PAGAMENTO_FUNCIONARIO 4, 496.63, NULL, 496.63, '2018-09-29', 0, '20181128 02:01:13'
GO
	EXEC GRAVA_PAGAMENTO_FUNCIONARIO 3, 521, NULL, 521, '2018-12-30', 0, '20181128 02:01:14'
GO
	EXEC GRAVA_PAGAMENTO_FUNCIONARIO 1, 498, 56, 554, '2018-10-30', 0, '20181128 02:01:15'
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PAGAMENTO_FUNCIONARIO @CODIGO INT,  @COD_FUNCIONARIO INT, @VALOR_FIXO MONEY, @VALOR_EXTRA MONEY, 
											  @TOTAL MONEY, @DATA DATE, @STATUS BIT
AS
    BEGIN
       UPDATE TB_PAGAMENTO_FUNCIONARIO
	   SET COD_FUNCIONARIO_PAGAMENTO=@COD_FUNCIONARIO, VALORFIXO_PAGAMENTO=@VALOR_FIXO, 
	   VALOREXTRA_PAGAMENTO=@VALOR_EXTRA, TOTAL_PAGAMENTO=@TOTAL, DATA_PAGAMENTO=@DATA, STATUS_PAGAMENTO=@STATUS
       WHERE COD_PAGAMENTO = @CODIGO 
       DECLARE @ULTIMO_PF INT
	   SET @ULTIMO_PF = SCOPE_IDENTITY()
	   RETURN @ULTIMO_PF
    END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_AGENDAMENTO, TB_DENTISTA, TB_PACIENTE, TB_TRATAMENTO
WHERE COD_DENTISTA=DENTISTA_AGENDAMENTO AND COD_PACIENTE=PACIENTE_AGENDAMENTO AND COD_TRATAMENTO=TRATAMENTO_AGENDAMENTO

GO

CREATE PROCEDURE ALTERA_AGENDAMENTO_BIT @CODIGO INT
AS
	BEGIN 	
		UPDATE TB_AGENDAMENTO SET CONSULTA_AGENDAMENTO=1 WHERE COD_AGENDAMENTO = @CODIGO
	END	
	
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO

CREATE PROCEDURE GRAVA_LOG @DESCRICAO TEXT, @USUARIO INT, @DTHORA DATETIME 
AS
	BEGIN
		INSERT INTO TB_LOG
		VALUES(@DESCRICAO, @USUARIO, @DTHORA)
	END

----------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO

CREATE PROCEDURE CAIXA_AUTOMATICO @DATA DATE,@ENTRADA MONEY,@SAIDA MONEY,@DTCADASTRO DATETIME,@AVISTA INT,@APRAZO INT,@PARCELA INT,@DESPESA INT
AS
DECLARE @ENTRADAS MONEY, @SAIDAS MONEY, @SOMA MONEY
	BEGIN
		
		SET @ENTRADAS = ( SELECT SUM(ENTRADA_CAIXA)		FROM TB_CAIXA WHERE CAST(DTCADASTRO_CAIXA AS DATE) = @DATA);             
		
		SET @SAIDAS =	( SELECT SUM(SAIDA_CAIXA)		FROM TB_CAIXA WHERE CAST(DTCADASTRO_CAIXA AS DATE) = @DATA);
		
		
		---
		IF (@ENTRADAS is NULL) and (@SAIDAS is NULL)
		BEGIN
			SET @SOMA = @ENTRADA-@SAIDA;
	        select @soma;
		    INSERT INTO TB_CAIXA VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);
	    END
	   
	    
	    ELSE IF (@ENTRADAS is not NULL) and (@SAIDAS is NULL)
	    BEGIN
			SET @SOMA = @ENTRADAS + (@ENTRADA - @SAIDA)
		    INSERT INTO TB_CAIXA
		    VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);	    
	    END
	   
	    ---
	    ELSE IF (@ENTRADAS is NULL) and (@SAIDAS is not NULL)
	    BEGIN
			SET @SOMA = @SAIDAS + (@ENTRADA - @SAIDA)
		    INSERT INTO TB_CAIXA
		    VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);	    
	    END 
	   
	    ---
	    ELSE
	    BEGIN
			SET @SOMA = (@ENTRADAS - @SAIDAS) + @ENTRADA-@SAIDA;
		    INSERT INTO TB_CAIXA
		    VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);
		END
		
END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PAGAMENTO_DENTISTA @CODIGO_PAGAMENTO INT, @CODIGO_DENT INT, @VALOR MONEY, @DATA DATE, @STATUS BIT
AS
	BEGIN	
		UPDATE TB_PAGAMENTO_DENTISTA
		SET COD_DENTISTA=@CODIGO_DENT, VALOR_PAGAMENTO=@VALOR, DATA_PAGAMENTO=@DATA,STATUS_PAGAMENTO=@STATUS
		WHERE COD_PAGAMENTO=@CODIGO_PAGAMENTO 
	END 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	SELECT * FROM TB_AGENDAMENTO
GO

CREATE PROCEDURE ALTERA_AGENDAMENTO @CODIGO INT, @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, @CONSULTA BIT, @OBS TEXT
AS
BEGIN
	UPDATE TB_AGENDAMENTO SET DATAHORA_AGENDAMENTO=@DATAHORA, PACIENTE_AGENDAMENTO=@PACIENTE, DENTISTA_AGENDAMENTO=@DENTISTA, 
		TRATAMENTO_AGENDAMENTO=@TRATAMENTO,	CONSULTA_AGENDAMENTO=@CONSULTA, OBS_AGENDAMENTO=@OBS WHERE COD_AGENDAMENTO=@CODIGO
END

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE EXCLUI_CAIXA @CODIGO INT
AS
BEGIN
	DELETE TB_CAIXA WHERE DESPESAS_CAIXA=@CODIGO
END
	
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE EXCLUI_DESPESA @CODIGO INT
AS
BEGIN
	DELETE TB_DESPESA WHERE COD_DESPESA=@CODIGO
END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE ALTERA_CONSULTA @CODIGO INT, @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, @OBS TEXT
AS
BEGIN
	UPDATE TB_CONSULTA SET DATAHORA_CONSULTA=@DATAHORA, PACIENTE_CONSULTA=@PACIENTE, DENTISTA_CONSULTA=@DENTISTA,
						   TRATAMENTO_CONSULTA=@TRATAMENTO, OBS_CONSULTA=@OBS
	WHERE COD_CONSULTA=@CODIGO
END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE PAGA_FUNCIONARIO @CODIGO INT
AS
	BEGIN
		UPDATE TB_PAGAMENTO_FUNCIONARIO SET STATUS_PAGAMENTO=1 WHERE COD_PAGAMENTO=@CODIGO
	END
    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE PAGAMENTO_FUNC_EX @CODIGO INT 
AS
		DECLARE @PAGAMENTO INT, @CAIXA INT, @DESPESA INT
	BEGIN
		
		SET @DESPESA = ( SELECT COD_DESPESA FROM TB_DESPESA, TB_PAGAMENTO_FUNCIONARIO WHERE COD_PAGAMENTO=PAG_FUNCIONARIO
						AND COD_PAGAMENTO=@CODIGO )
		SET @CAIXA   = ( SELECT COD_CAIXA FROM TB_CAIXA, TB_DESPESA WHERE COD_DESPESA=DESPESAS_CAIXA AND 
						DESPESAS_CAIXA = @DESPESA )
		
		DELETE TB_CAIXA					WHERE COD_CAIXA=@CAIXA
		DELETE TB_DESPESA				WHERE COD_DESPESA=@DESPESA
		DELETE TB_PAGAMENTO_FUNCIONARIO WHERE COD_PAGAMENTO=@CODIGO
	
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	
GO
	
CREATE PROCEDURE PAGAMENTO_DENT_EX @CODIGO INT 
AS
		DECLARE @PAGAMENTO INT, @CAIXA INT, @DESPESA INT
	BEGIN
		
		SET @DESPESA = ( SELECT COD_DESPESA FROM TB_DESPESA, TB_PAGAMENTO_DENTISTA WHERE COD_PAGAMENTO=PAG_DENTISTA
						AND COD_PAGAMENTO=@CODIGO )
		SET @CAIXA   = ( SELECT COD_CAIXA FROM TB_CAIXA, TB_DESPESA WHERE COD_DESPESA=DESPESAS_CAIXA AND 
						DESPESAS_CAIXA = @DESPESA )
		
		DELETE TB_CAIXA					WHERE COD_CAIXA=@CAIXA
		DELETE TB_DESPESA				WHERE COD_DESPESA=@DESPESA
		DELETE TB_PAGAMENTO_DENTISTA	WHERE COD_PAGAMENTO=@CODIGO
	
	END	

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	
GO
	
CREATE PROCEDURE EXCLUI_AGENDAMENTO @CODIGO INT
AS
	BEGIN
	
		DELETE TB_CONSULTA WHERE PREAGENDAMENTO_CONSULTA = @CODIGO
		DELETE TB_AGENDAMENTO WHERE COD_AGENDAMENTO = @CODIGO
	
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE EXCLUI_CONSULTA @CODIGO INT
AS
	BEGIN
		
		DELETE TB_CONSULTA WHERE COD_CONSULTA=@CODIGO
		
	END

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PRODUTO_CX_DP @CODIGO INT 
AS
		DECLARE @SAIDA_NOVA MONEY, @DESPESA INT--, @TOTAL_CAIXA MONEY, @SAIDA_ANTERIOR MONEY, @TOTAL_CAIXA_NOVO MONEY
	BEGIN
		
		SET @DESPESA = ( SELECT COD_DESPESA FROM TB_DESPESA, TB_PRODUTO WHERE COD_PRODUTO=PRODUTO_DESPESA
						 AND COD_PRODUTO=@CODIGO )
						
		SET @SAIDA_NOVA = (SELECT TOTAL_PRODUTO FROM TB_PRODUTO WHERE COD_PRODUTO=@CODIGO)
		
		UPDATE TB_CAIXA
		SET SAIDA_CAIXA = @SAIDA_NOVA
		WHERE DESPESAS_CAIXA = @DESPESA
		
		UPDATE TB_DESPESA
		SET VALOR_DESPESA = @SAIDA_NOVA
		WHERE PRODUTO_DESPESA = @CODIGO
	
	END

GO
	
CREATE PROCEDURE ALTERA_PARCELAS_PACIENTE @CODIGO INT, @COD_PARCELAMENTO INT, @DATAPAGAMENTO DATE, @DATAVENCIMENTO DATE, @ENTRADA BIT, @OBS TEXT
AS
	BEGIN
		UPDATE TB_PARCELA
		SET COD_PARCELAMENTO=@COD_PARCELAMENTO, DATAPAGAMENTO_PARCELA=@DATAPAGAMENTO, 
		DATAVENCIMENTO_PARCELA=@DATAVENCIMENTO, ENTRADA_PARCELA=@ENTRADA, OBS_PARCELA=@OBS 
		WHERE COD_PARCELA=@CODIGO
     END	

GO

CREATE PROCEDURE PAGA_PARCELAS_PACIENTE @CODIGO INT, @VALOR MONEY, @DESCONTO MONEY, @STATUS_PARCELA BIT, @DATA DATE --1=PAGO, 0=PENDENTE
										
AS
	BEGIN
		UPDATE TB_PARCELA
		SET  VALOR_PARCELA=@VALOR, DESCONTO_PARCELA=@DESCONTO, STATUS_PARCELA=@STATUS_PARCELA, DATAPAGAMENTO_PARCELA=@DATA
		WHERE COD_PARCELA=@CODIGO
     END
     
GO

CREATE PROCEDURE RESTAURACAO @CAMINHO VARCHAR (50)
										
AS
	BEGIN
	    
		RESTORE DATABASE TCC FROM DISK = @CAMINHO
     END	
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- SELECT * FROM TB_PAGAMENTO_PACIENTE_PARCELADO

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	
/*GO
	
CREATE PROCEDURE FECHA_CAIXA 
AS
	BEGIN
	
		DELETE TB_CAIXA
	
	END*/