-- CRIE O BANCO CIDADE_ESTADO PRIMEIRO
-- APENAS APERTE O "F5" 

USE TCC
GO

ALTER AUTHORIZATION ON DATABASE :: TCC TO SA

CREATE TABLE TB_RESPONSAVEL
(
	COD_RESPONSAVEL					INT IDENTITY PRIMARY KEY,
	NOME_RESPONSAVEL	  			VARCHAR(50) NOT NULL,
	RG_RESPONSAVEL					VARCHAR(13) NOT NULL,
	CPF_RESPONSAVEL					CHAR (15) NOT NULL, 
	SEXO_RESPONSAVEL				CHAR NOT NULL,
	TEL_RESPONSAVEL					VARCHAR(15) NOT NULL,
	ENDERECO_RESPONSAVEL			VARCHAR(100) NOT NULL,
	EMAIL_RESPONSAVEL				VARCHAR(30),
	CIDADE_RESPONSAVEL				INT FOREIGN KEY REFERENCES TB_CIDADE(CD_CIDADE) NOT NULL,
	NASCIMENTO_RESPONSAVEL			DATE NOT NULL,
	STATUS_RESPONSAVEL				BIT NOT NULL,
	DTHORACADASTRO_RESPONSAVEL		DATETIME NOT NULL
)

GO

CREATE TABLE TB_PACIENTE
(
	COD_PACIENTE			INT IDENTITY PRIMARY KEY,
	NOME_PACIENTE			VARCHAR(50) NOT NULL,
	RG_PACIENTE				VARCHAR(13) NULL,
	CPF_PACIENTE			CHAR (15) NULL, 
	SEXO_PACIENTE			CHAR NOT NULL,
	NASCIMENTO_PACIENTE		DATE NOT NULL,
	ENDERECO_PACIENTE		VARCHAR(100) NOT NULL,
	EMAIL_PACIENTE			VARCHAR(30),
	CIDADE_PACIENTE			INT FOREIGN KEY REFERENCES TB_CIDADE(CD_CIDADE) NOT NULL,
	TEL1_PACIENTE			VARCHAR(15) NOT NULL,
	TEL2_PACIENTE	  		VARCHAR(15) NULL,
	MENORDE18ANOS			BIT NOT NULL,
	RESPONSAVEL_PACIENTE	INT FOREIGN KEY REFERENCES TB_RESPONSAVEL(COD_RESPONSAVEL),
	OBS_PACIENTE			TEXT NULL,
	STATUS_PACIENTE			BIT NOT NULL,
	DTHORACADASTRO_PACIENTE	DATETIME NOT NULL
)

GO

CREATE TABLE TB_DENTISTA
(
	COD_DENTISTA			 INT IDENTITY PRIMARY KEY,
	NOME_DENTISTA			 VARCHAR(50) NOT NULL,
	SEXO_DENTISTA			 CHAR NOT NULL,
	CRO_DENTISTA			 VARCHAR(6) NOT NULL,
	EMAIL_DENTISTA			 VARCHAR(30),
	STATUS_DENTISTA			 CHAR NOT NULL,
	DTHORACADASTRO_DENTISTA  DATETIME NOT NULL
)

GO

CREATE TABLE TB_FUNCIONARIO
(
	COD_FUNCIONARIO				INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_FUNCIONARIO			VARCHAR(50) NOT NULL,
	SEXO_FUNCIONARIO			CHAR NOT NULL,
	NASCIMENTO_FUNCIONARIO		DATE NOT NULL,
	RG_FUNCIONARIO				VARCHAR(13) NOT NULL,
	CPF_FUNCIONARIO				CHAR(15) NOT NULL,
	ENDERECO_FUNCIONARIO		VARCHAR(50) NOT NULL,
	EMAIL_FUNCIONARIO			VARCHAR(30),
	CIDADE_FUNCIONÁRIO			INT FOREIGN KEY REFERENCES TB_CIDADE(CD_CIDADE) NOT NULL,
	TEL1_FUNCIONARIO			VARCHAR(15) NOT NULL,
	TEL2_FUNCIONARIO			VARCHAR(15) NULL,
	STATUS_FUNCIONARIO			BIT NOT NULL,
	DTHORACADASTRO_FUNCIONARIO  DATETIME NOT NULL
)

GO

CREATE TABLE TB_USUARIO	
(
	COD_USUARIO				 INT IDENTITY PRIMARY KEY,
	NOME_USUARIO			 VARCHAR(50) NOT NULL,
	LOGIN_USUARIO			 VARCHAR(15) NOT NULL,
	SENHA_USUARIO			 VARCHAR(10) NOT NULL,
	FUNCIONARIO_USUARIO		 INT FOREIGN KEY REFERENCES TB_FUNCIONARIO(COD_FUNCIONARIO) NULL,
	DENTISTA_USUARIO		 INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NULL,
	TIPO_USUARIO			 BIT NOT NULL,
	STATUS_USUARIO			 BIT NOT NULL,
	DTHORACADASTRO_USUARIO   DATETIME NOT NULL
)

GO

CREATE TABLE TB_LOG
(
	COD_LOG					INT IDENTITY PRIMARY KEY,
	DESCRICAO_LOG			VARCHAR(250) , 
	USUARIO_LOG				INT FOREIGN KEY REFERENCES TB_USUARIO(COD_USUARIO),
	DTHORA_LOG				DATETIME NOT NULL
)

GO

CREATE TABLE TB_PRODUTO
(
	COD_PRODUTO				INT IDENTITY PRIMARY KEY,
	NOME_PRODUTO			VARCHAR(15) NOT NULL,
	DENTISTA_PRODUTO		INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NULL,
	PRECOUNITARIO_PRODUTO	MONEY NOT NULL,
	TIPO_PRODUTO			VARCHAR(15) NOT NULL,
	VALIDADE_PRODUTO		DATE NULL,
	DATAPAGAMENTO_PRODUTO	DATE NOT NULL,
	QUANTIA_PRODUTO			INT NOT NULL,
	TOTAL_PRODUTO			MONEY NOT NULL,
	DTHORACADASTRO_PRODUTO  DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_DENTISTA -- MUDAR NOME DO CAMPO PARA COD_DENTISTA
(
	COD_PAGAMENTO				INT IDENTITY PRIMARY KEY,
	COD_DENTISTA				INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	VALOR_PAGAMENTO				MONEY NOT NULL,
	DATA_PAGAMENTO				DATE NOT NULL,
	STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_PAGAMENTO	DATETIME NOT NULL	
)

GO

CREATE TABLE TB_PAGAMENTO_FUNCIONARIO
(
	COD_PAGAMENTO				 INT IDENTITY PRIMARY KEY NOT NULL,
	COD_FUNCIONARIO_PAGAMENTO	 INT FOREIGN KEY REFERENCES TB_FUNCIONARIO(COD_FUNCIONARIO) NOT NULL,	
	VALORFIXO_PAGAMENTO			 MONEY NOT NULL,
	VALOREXTRA_PAGAMENTO		 MONEY NULL,
	TOTAL_PAGAMENTO				 MONEY NOT NULL,
	DATA_PAGAMENTO				 DATE NOT NULL,
	STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_PAGAMENTO	 DATETIME NOT NULL
)

GO

CREATE TABLE TB_DESPESA		
(	
	COD_DESPESA				INT IDENTITY PRIMARY KEY,
	TIPO_DESPESA			VARCHAR(20),
	PRODUTO_DESPESA			INT FOREIGN KEY REFERENCES TB_PRODUTO(COD_PRODUTO) NULL,
	PAG_FUNCIONARIO			INT FOREIGN KEY REFERENCES TB_PAGAMENTO_FUNCIONARIO(COD_PAGAMENTO) NULL,
	PAG_DENTISTA			INT FOREIGN KEY REFERENCES TB_PAGAMENTO_DENTISTA(COD_PAGAMENTO) NULL,
	VALOR_DESPESA			MONEY NOT NULL,
	DATAPAGAMENTO_DESPESA	DATE NOT NULL,
	OBS_DESPESA				TEXT NULL,
	DTHORACADASTRO_DESPESA  DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_PACIENTE_AVISTA
(
	COD_AVISTA					INT IDENTITY PRIMARY KEY,
	PACIENTE_AVISTA				INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_AVISTA				INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	VALOR_AVISTA				MONEY NOT NULL,
	DATAPAGAMENTO_AVISTA		DATE NOT NULL,
	TIPO_AVISTA					VARCHAR(15) NOT NULL,
		STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_AVISTA       DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_PACIENTE_APRAZO
(
	COD_APRAZO					INT IDENTITY PRIMARY KEY,
	PACIENTE_APRAZO				INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_APRAZO				INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	VALOR_APRAZO				MONEY NOT NULL,
	DATAPAGAMENTO_APRAZO		DATE NOT NULL, -- ESSA TABELA NAO TEM STATUS ENTAO TEM QUE REPENSAR
	TIPO_APRAZO					VARCHAR(15) NOT NULL,
	OBS_APRAZO					TEXT, 
		STATUS_PAGAMENTO			BIT NOT NULL,
	DTHORACADASTRO_APRAZO       DATETIME NOT NULL
)

GO

CREATE TABLE TB_PAGAMENTO_PACIENTE_PARCELADO
(
	COD_PARCELAMENTO			INT IDENTITY PRIMARY KEY NOT NULL,
	PACIENTE_PARCELAMENTO		INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_PARCELAMENTO		INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	TIPO_PARCELAMENTO			VARCHAR(15) NOT NULL, -- SE É CARTÃO, CARNÊN OU OUTRO
	VALOR_TOTAL					MONEY NOT NULL,
	QUANTIA_PARCELAS			INT NOT NULL,
	OBS_PARCELAMENTO			TEXT, ------------------------------
	DTHORACADASTRO_PARCELADO	DATETIME NOT NULL
)

GO

CREATE TABLE TB_PARCELA
(
	COD_PARCELA					INT IDENTITY PRIMARY KEY,
	COD_PARCELAMENTO			INT FOREIGN KEY REFERENCES TB_PAGAMENTO_PACIENTE_PARCELADO(COD_PARCELAMENTO) NOT NULL,
	DATAPAGAMENTO_PARCELA		DATE NULL,
	DATAVENCIMENTO_PARCELA		DATE NOT NULL,
	ENTRADA_PARCELA				BIT NULL,
	VALOR_PARCELA				MONEY NOT NULL, 
	DESCONTO_PARCELA			MONEY NULL,
	STATUS_PARCELA				BIT NOT NULL,
	OBS_PARCELA 				TEXT , 
	DTHORACADASTRO_PARCELA      DATETIME NOT NULL	
)

GO 

CREATE TABLE TB_TRATAMENTO
(
	COD_TRATAMENTO				INT IDENTITY PRIMARY KEY,
	NOME_TRATAMENTO				VARCHAR(20) NOT NULL,
	OBS_TRATAMENTO				TEXT,
	DTHORACADASTRO_TRATAMENTO	DATETIME NOT NULL
)

GO

CREATE TABLE TB_AGENDAMENTO
(
	COD_AGENDAMENTO				  INT IDENTITY PRIMARY KEY,
	DATAHORA_AGENDAMENTO		  DATETIME NOT NULL,
	PACIENTE_AGENDAMENTO		  INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_AGENDAMENTO		  INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	TRATAMENTO_AGENDAMENTO		  INT FOREIGN KEY REFERENCES TB_TRATAMENTO(COD_TRATAMENTO) NOT NULL,
	CONSULTA_AGENDAMENTO		  BIT,
	OBS_AGENDAMENTO				  TEXT NULL,
	DTHORACADASTRO_AGENDAMENTO    DATETIME NOT NULL
) 

GO

CREATE TABLE TB_CONSULTA
(
	COD_CONSULTA				INT IDENTITY PRIMARY KEY,
	DATAHORA_CONSULTA			DATETIME NOT NULL,
	PACIENTE_CONSULTA			INT FOREIGN KEY REFERENCES TB_PACIENTE(COD_PACIENTE) NOT NULL,
	DENTISTA_CONSULTA			INT FOREIGN KEY REFERENCES TB_DENTISTA(COD_DENTISTA) NOT NULL,
	TRATAMENTO_CONSULTA			INT FOREIGN KEY REFERENCES TB_TRATAMENTO(COD_TRATAMENTO) NOT NULL,
	PREAGENDAMENTO_CONSULTA		INT FOREIGN KEY REFERENCES TB_AGENDAMENTO(COD_AGENDAMENTO)NULL,	
	OBS_CONSULTA				TEXT NULL,
	DTHORACADASTRO_CONSULTA		DATETIME NOT NULL
)

GO

CREATE TABLE TB_CAIXA
(
	COD_CAIXA					INT IDENTITY PRIMARY KEY,
	ENTRADA_CAIXA				MONEY NOT NULL,
	SAIDA_CAIXA					MONEY NOT NULL,
	TOTAL_CAIXA					MONEY NOT NULL,
	DTCADASTRO_CAIXA			DATETIME NOT NULL,
	PAGAMENTOS_AVISTA_CAIXA		INT FOREIGN KEY REFERENCES TB_PAGAMENTO_PACIENTE_AVISTA(COD_AVISTA) NULL,
	PAGAMENTOS_APRAZO_CAIXA		INT FOREIGN KEY REFERENCES TB_PAGAMENTO_PACIENTE_APRAZO(COD_APRAZO) NULL,
	PAGAMENTOS_PARCELAS_CAIXA	INT FOREIGN KEY REFERENCES TB_PARCELA (COD_PARCELA) NULL,
	DESPESAS_CAIXA				INT FOREIGN KEY REFERENCES TB_DESPESA (COD_DESPESA) NULL
)	


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE GRAVA_CAIXA @ENTRADA MONEY, @SAIDA MONEY,  @TOTAL MONEY, @DT_CADASTRO DATE, @AVISTA INT, @APRAZO INT, @PARCELAS INT, @DESPESAS INT
AS
	BEGIN
	
		INSERT INTO TB_CAIXA
		VALUES(@ENTRADA, @SAIDA, @TOTAL, @DT_CADASTRO, @AVISTA, @APRAZO, @PARCELAS, @DESPESAS)
	
	END	

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_TRATAMENTO @NOME VARCHAR(20), @OBS TEXT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_TRATAMENTO
		VALUES (@NOME, @OBS, @DTHORA_CADASTRO)
		
		DECLARE @ULTIMO_TRAT INT;
		SET @ULTIMO_TRAT = SCOPE_IDENTITY()
		RETURN @ULTIMO_TRAT ; 
	END

GO

	EXEC GRAVA_TRATAMENTO 'ORTODONTIA', null, '20180615 15:30:42'
GO

	EXEC GRAVA_TRATAMENTO 'DENTÍSTICA', null, '20180820 10:01:25'
GO

	EXEC GRAVA_TRATAMENTO 'ENDODONTIA', null, '20181030 20:12:28'
GO

	EXEC GRAVA_TRATAMENTO 'IMPLANTODONTIA', null, '20181025 22:52:02'
GO

	EXEC GRAVA_TRATAMENTO 'PERIODONTIA', null, '20181112 13:30:12'

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_TRATAMENTO @CODIGO INT, @NOME VARCHAR(20), @OBS TEXT
AS
    BEGIN
       UPDATE TB_TRATAMENTO
       SET NOME_TRATAMENTO = @NOME, OBS_TRATAMENTO = @OBS
       WHERE COD_TRATAMENTO = @CODIGO

	   	DECLARE @ULTIMO_TRAT INT;
		SET @ULTIMO_TRAT = SCOPE_IDENTITY()
		RETURN @ULTIMO_TRAT ; 
    END

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO 

CREATE PROCEDURE GRAVA_DENTISTA @NOME VARCHAR(50), @SEXO CHAR, @CRO VARCHAR(6), @EMAIL VARCHAR(30), @STATUS BIT, @DTHORACADASTRO_DENTISTA DATETIME
AS
	BEGIN
		INSERT INTO TB_DENTISTA
		VALUES(@NOME, @SEXO, @CRO, @EMAIL, @STATUS, @DTHORACADASTRO_DENTISTA)
	  
	    DECLARE @ULTIMO_DENT INT;
		SET @ULTIMO_DENT = SCOPE_IDENTITY()
		RETURN @ULTIMO_DENT ; 	
	END	

GO
	
	EXEC GRAVA_DENTISTA 'RENATA',  'F',  '564789',  'renataprofss18@outlook.com', 1, '20180615 15:30:48'
GO

	EXEC GRAVA_DENTISTA 'GIULIANO', 'M', '654546', 'giulianoprofissional@hotmail.com', 1, '20180615 15:40:28'
GO

	EXEC GRAVA_DENTISTA 'PATRÍCIA', 'F', '321645', 'patriciapereira23@gmail.com', 0, '20181123 07:12:41'
GO

	EXEC GRAVA_DENTISTA 'PEDRO', 'M', '714258', 'predo_carvalho@outlook.com', 1, '20181021 14:20:20'
GO

	EXEC GRAVA_DENTISTA 'CLARA', 'F', '312987', 'clarinhasilva25@gmail.com', 1, '20180120 19:28:21'
GO

	EXEC GRAVA_DENTISTA 'MAURÍCIO', 'M', '693825', 'mauricioricardo235@hotmail.com', 0, '20181021 10:27:35'
GO

	EXEC GRAVA_DENTISTA 'MARIANA', 'F', '741639', 'marianaalmeida15@hotmail.com', 1, '20180514 09:44:42'
GO

	EXEC GRAVA_DENTISTA 'OSVALDO', 'M', '951375', 'osvaldo_carlos@outlook.com', 0, '20180815 09:10:24'
GO


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_DENTISTA @CODIGO INT,  @NOME VARCHAR(50), @SEXO CHAR, @CRO VARCHAR(6), @EMAIL VARCHAR(30), @STATUS BIT
AS
	BEGIN
	   UPDATE TB_DENTISTA
	   SET NOME_DENTISTA = @NOME, SEXO_DENTISTA = @SEXO, CRO_DENTISTA = @CRO, EMAIL_DENTISTA=@EMAIL, STATUS_DENTISTA = @STATUS
	   WHERE COD_DENTISTA = @CODIGO

	    DECLARE @ULTIMO_DENT INT;
		SET @ULTIMO_DENT = SCOPE_IDENTITY()
		RETURN @ULTIMO_DENT ; 	
	END

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO 

CREATE PROCEDURE GRAVA_RESPONSAVEL @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR(15), @SEXO CHAR, @TELEFONE VARCHAR(15), 
								   @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @NASCIMENTO DATE, @STATUS BIT, @DTHORA_CADASTRO DATETIME 
AS 
	BEGIN
		INSERT INTO TB_RESPONSAVEL
		VALUES (@NOME, @RG, @CPF, @SEXO, @TELEFONE, @ENDERECO, @EMAIL, @CIDADE, @NASCIMENTO, @STATUS, @DTHORA_CADASTRO)
		
		DECLARE @ULTIMO_R INT;
		SET @ULTIMO_R = SCOPE_IDENTITY()
		RETURN @ULTIMO_R ; 
	END

GO

	EXEC GRAVA_RESPONSAVEL 'CARLOS LUCAS VARRASCHIN', '22.321.008-3', '28835324631', 'M', '(15)99837-2291', 'RUA SANTA CATARINA, 223', 'carlosluucas@gmail.com', 1813, '1997-02-10', 1, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'CAMILA LUIZA FERRAZ', '25.084.716-4', '89601385843', 'F', '(14)99838-1150', 'RUA DIREITA, 430', 'marlenefranciscaaragao_@outlook.com', 9475, '1998-06-01', 1, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'JOÃO PEDRO MALAGODI', '17.543.958-8', '70770481876', 'M', '(14)98989-4483', 'RUA PEDRO ALCÂNTRA RIBEIRO, 193', 'filipegaelassis__filipegaelassis@hotmail.com.br', 9475, '1991-02-21', 0, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'ISADORA MARIA PEREIRA', '45.926.874-1', '45826349824', 'F', '(15)99803-2997', 'RUA SANTA CATARINA, 223', 'isadoraperereira@hotmail.com', 7583, '1986-04-25', 1, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'RICARO CAIO PIRES', '48.073.002-7', '44413077806', 'M', '(14)98881-8364', 'RUA MAREHAL FLORIANO PEIXOTO, 1032', 'jjoaoricardocalebepires@gmail.com', 9475, '1992-11-04', 1, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'MARIA CLARA FERRAZ', '49.815.840-8', '48785137804', 'F', '(14)99740-8032', 'RUA ANTÔNIO CARNIATO, 228', 'maria_clara95@outlook.com', 7583, '1985-06-25', 1, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'ELIAS BRYAN ANDERSON RAMOS', '22.321.008-3', '95492450808', 'M', '(15)99851-0215', 'RUA XV DE NOVEMBRO, 1168', 'eliasbryanandersonramos@hotmail.com', 1813, '1989-05-23', 0, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'EMILLY ESTER LIMA', '16.849.754-2', '32019910829', 'F', '(14)99657-4906', 'RUA DILSON FUNARO, 157', 'eemillyesterlima@outlook.com', 1813, '1997-02-10', 1, '20181121 13:20:12'
GO

	EXEC GRAVA_RESPONSAVEL 'NELSON CALEB DE PAULA', '33.027.595-1', '83850284808', 'M', '(15)98678-5750', 'RUA SÁGITÁRIO, 553', 'nnelsoncalebdepaula@outlook.com', 7583, '1996-11-14', 1, '20151012 15:05:56'
GO

	EXEC GRAVA_RESPONSAVEL 'SUELI FLÁVIA FIGUEIREDO', '45.397.996-8', '31101233800', 'F', '(15)99621-6059', 'RUA ONÇA-PINTADA, 988', 'suelijenniferflaviafigueiredo_@gmail.com', 1813, '1986-05-12', 1, '20181021 13:20:12'
GO

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE ALTERA_RESPONSAVEL @CODIGO INT, @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR(15), @SEXO CHAR, @TELEFONE VARCHAR(15), 
								   @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @NASCIMENTO DATE, @STATUS BIT
AS 
	BEGIN
	   UPDATE TB_RESPONSAVEL
	   SET NOME_RESPONSAVEL = @NOME, RG_RESPONSAVEL = @RG, CPF_RESPONSAVEL = @CPF, SEXO_RESPONSAVEL = @SEXO, 
	       TEL_RESPONSAVEL = @TELEFONE,ENDERECO_RESPONSAVEL = @ENDERECO, EMAIL_RESPONSAVEL = @EMAIL, CIDADE_RESPONSAVEL= @CIDADE, 
	       NASCIMENTO_RESPONSAVEL = @NASCIMENTO, STATUS_RESPONSAVEL = @STATUS
	   WHERE COD_RESPONSAVEL = @CODIGO

		DECLARE @ULTIMO_R INT;
		SET @ULTIMO_R = SCOPE_IDENTITY()
		RETURN @ULTIMO_R ; 
	END    

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO -----------STATUS-----------

CREATE PROCEDURE GRAVA_PAGAMENTO_DENTISTA @CODIGO_DENTISTA INT, @VALOR MONEY, @DATA_PAGAMENTO DATE, @STATUS BIT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_DENTISTA
		VALUES(@CODIGO_DENTISTA, @VALOR, @DATA_PAGAMENTO, @STATUS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_PAG INT;
		SET @ULTIMO_PAG = SCOPE_IDENTITY()
		RETURN @ULTIMO_PAG ; 
	END

select*from TB_PAGAMENTO_DENTISTA
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 1, 1289, '2018-07-31', 1, '20180725 12:24:56'
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 1, 1150.85, '2018-08-31', 1, '20180824 10:05:32'
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 1, 1142.14, '2018-09-30', 1, '20180929 14:36:04'
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 1, 1140, '2018-10-30', 1, '20181028 15:01:45'
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 8, 1141.24, '2018-09-30', 1, '20180928 10:05:32'
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 3, 1125.65, '2018-12-30', 0, '20181229 11:25:42'
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 6, 1300, '2018-11-30', 0, '20181128 10:05:32'
GO

	EXEC GRAVA_PAGAMENTO_DENTISTA 4, 1025.50, '2018-11-29', 0, '20181127 10:05:32'

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GO 

CREATE PROCEDURE GRAVA_FUNCIONARIO @NOME VARCHAR(50), @SEXO CHAR, @NASCIMENTO DATE, @RG VARCHAR(13), 
								   @CPF CHAR (15), @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, 
								   @TELEFONE VARCHAR(15), @TELEFONE2 VARCHAR(15), @STATUS BIT, @DTHORA_CADASTRO DATETIME
AS 
	BEGIN
		INSERT INTO TB_FUNCIONARIO
		VALUES (@NOME, @SEXO, @NASCIMENTO, @RG, @CPF, @ENDERECO, @EMAIL, @CIDADE, @TELEFONE, @TELEFONE2, @STATUS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_F INT;
		SET @ULTIMO_F = SCOPE_IDENTITY()
		RETURN @ULTIMO_F ; 
	END 

GO

	EXEC GRAVA_FUNCIONARIO 'MICHELE', 'F', '1990-05-23', '45.195.264-8', '99854749886', 'RUA XV DE NOVEMBRO, 1168', NULL, 9463, '(15)99751-4549', NULL, 1, '20170620 15:05:23'
GO

	EXEC GRAVA_FUNCIONARIO 'AMANDA LUNA DA ROSA', 'F', '1993-06-05', '29.290.459-9', '36975437840', 'RUA ELENI TELLES PEREIRA GUARIBA, 920', 'amandalunadarosa.@gmail.com', 9463, '(14)99852-5698', '(14)99758-9832', 1, '20170620 15:05:23'
GO

	EXEC GRAVA_FUNCIONARIO 'FLÁVIA BETINA CARLA SANTOS', 'F', '1993-01-08', '20.760.620-1', '61685865801', 'RUA JOSÉ FRANCISCO BRANDÃO, 943', 'flaviabetinacarlasantos_@hotmail.com', 7583, '(14)99852-0564', NULL, 1, '20180512 14:24:12'
GO

	EXEC GRAVA_FUNCIONARIO 'JOAQUIM FRANCISCO KAUÊ DA PAZ', 'M', '1993-09-24', '22.355.100-4', '38693078895', 'RUA JOSÉ BATISTA DE SOUZA, 620', NULL, 1813, '(14)99645-2847', '(14)99878-0215', 0, '20161023 08:52:46'
GO

	EXEC GRAVA_FUNCIONARIO 'SILVANA ANTÔNIA JULIA NASCIMENTO', 'F', '1993-04-08', '26.913.067-6', '91522483802', 'RUA ALPONT, 624', 'silvanaantoniajulianascimento_@outlook.com', 7583, '(15)99785-0454', '(15)99856-5871', 1, '20180125 10:23:06'

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_FUNCIONARIO @CODIGO INT, @NOME VARCHAR(50), @SEXO CHAR, @NASCIMENTO DATE, @RG VARCHAR(13), 
								   @CPF CHAR (15), @ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, 
								   @TELEFONE VARCHAR(15), @TELEFONE2 VARCHAR(15), @STATUS BIT
AS
    BEGIN
       UPDATE TB_FUNCIONARIO
       SET NOME_FUNCIONARIO = @NOME, SEXO_FUNCIONARIO = @SEXO, NASCIMENTO_FUNCIONARIO = @NASCIMENTO, RG_FUNCIONARIO = @RG,
           CPF_FUNCIONARIO = @CPF, ENDERECO_FUNCIONARIO = @ENDERECO, EMAIL_FUNCIONARIO = @EMAIL, CIDADE_FUNCIONÁRIO = @CIDADE,
           TEL1_FUNCIONARIO = @TELEFONE, TEL2_FUNCIONARIO = @TELEFONE2, STATUS_FUNCIONARIO = @STATUS
       WHERE COD_FUNCIONARIO = @CODIGO
	   	
		DECLARE @ULTIMO_F INT;
		SET @ULTIMO_F = SCOPE_IDENTITY()
		RETURN @ULTIMO_F ; 
    END	
	  

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PACIENTE @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR (15), @SEXO CHAR, @NASCIMENTO DATE,  
								@ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @TELEFONE VARCHAR(15), 
								@TELEFONE2 VARCHAR(15), @MENOR_DE_18 BIT, @RESPONSAVEL INT, @OBS TEXT, @STATUS BIT, 
								@DTHORA_CADASTRO datetime
AS
	BEGIN
		INSERT INTO TB_PACIENTE 
		VALUES(@NOME, @RG, @CPF, @SEXO, @NASCIMENTO, @ENDERECO, @EMAIL, @CIDADE, @TELEFONE, @TELEFONE2, @MENOR_DE_18, 
			   @RESPONSAVEL, @OBS, @STATUS, @DTHORA_CADASTRO)
			   
		DECLARE @ULTIMO_PACIENTE INT;
		SET @ULTIMO_PACIENTE = SCOPE_IDENTITY()
		RETURN @ULTIMO_PACIENTE ;
	END 

GO

	EXEC GRAVA_PACIENTE 'MARIANA ANDRADE', '16.388.047-5', '43903201065', 'F', '2001-09-22', 'SITIO SÃO BERNARDO', NULL, 7583, '(14)99955-6661' , NULL, 0, NULL, NULL, 1, '20181121 14:46:51'
GO

	EXEC GRAVA_PACIENTE 'ALICE MARIA RODRIGUES', '46.765.267-3', '07530454005', 'F', '1993-03-11', 'RUA ÁGATA, 142', NULL, 8614, '(14)99889-3056' , NULL, 0, NULL, NULL, 0, '20180628 11:36:34'
GO

	EXEC GRAVA_PACIENTE 'THALES EDSON CALEBE FERNANDES', '38.706.900-8', '87920255872', 'M', '1993-08-25', 'RUA DOS GUAICURUS, 544', 'thales_calebe@hotmail.com', 9475, '(14)98862-8118' , NULL, 0, NULL, NULL, 1, '20180628 15:04:00'
GO

	EXEC GRAVA_PACIENTE 'ANALU MARIA CARDOSO', '47.517.669-8', '26893147899', 'F', '2003-02-28', 'RUA KATENGE, 365', NULL, 7583, '(15)98840-6470' , NULL, 1, 2, NULL, 1, '20181025 09:25:19'
GO

	EXEC GRAVA_PACIENTE 'HEITOR ISSAC MENDES', '21.095.942-3', '21827005874', 'M', '1994-03-02', 'RUA VICENTE LEPORACE, 777', 'heitormendes_0302@outlook.com', 7583, '(14)99889-3056' , '(14)99815-4826', 0, NULL, NULL, 0, '20180628 18:43:58'
GO

	EXEC GRAVA_PACIENTE 'RICARDO CALEBE ENRICO NOVAES', '31.062.839-8', '33117109838', 'M', '1998-05-02', 'RUA WALDOMIRO SIQUEIRA, 20', NULL, 9463, '(14)998707-5791' , NULL, 0, NULL, NULL, 1, '20181021 09:21:02'
GO

	EXEC GRAVA_PACIENTE 'PEDRO IAGO MARCOS VINICIUS SOUZA', '21.350.041-3', '28431036818', 'M', '1994-11-15', 'RUA ERIDANO, 53', NULL, 7583, '(15)99684-9028' , NULL, 1, 3, NULL, 1, '20181111 10:05:37'
GO

	EXEC GRAVA_PACIENTE 'ELZA GIOVANA GABRIELA ALMADA', '14.259.646-2', '26294117887', 'F', '1992-04-24', 'RUA CIRO LAGAZZI, 159', 'elzagiovanagabrielaalmada.@gmail.com', 1813, '(14)99856-1187' , '(14)99847-4128', 0, NULL, NULL, 0, '20180926 13:53:43'
GO

	EXEC GRAVA_PACIENTE 'NAIR LUANA DA ROSA', '42.685.087-7', '36117712871', 'F', '1988-02-01', 'RUA MARIA DO CARMO DE OLIVEIRA, 41', NULL, 1813, '(14)99261-9462' , NULL, 0, NULL, NULL, 1, '20180831 15:45:20'


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PACIENTE @CODIGO INT, @NOME VARCHAR(50), @RG VARCHAR(13), @CPF CHAR (15), @SEXO CHAR, @NASCIMENTO DATE,  
								@ENDERECO VARCHAR(30), @EMAIL VARCHAR(30), @CIDADE INT, @TELEFONE VARCHAR(15), 
								@TELEFONE2 VARCHAR(15), @MENOR_DE_18 BIT, @RESPONSAVEL INT, @OBS TEXT, @STATUS BIT
AS
	BEGIN

	  UPDATE TB_PACIENTE
	  SET NOME_PACIENTE = @NOME, RG_PACIENTE = @RG, CPF_PACIENTE = @CPF, SEXO_PACIENTE = @SEXO, 
	      NASCIMENTO_PACIENTE = @NASCIMENTO,ENDERECO_PACIENTE = @ENDERECO, EMAIL_PACIENTE = @EMAIL, 
	      CIDADE_PACIENTE = @CIDADE, TEL1_PACIENTE = @TELEFONE, TEL2_PACIENTE = @TELEFONE2, 
	      MENORDE18ANOS = @MENOR_DE_18, RESPONSAVEL_PACIENTE = @RESPONSAVEL, OBS_PACIENTE = @OBS, 
	      STATUS_PACIENTE = @STATUS
      WHERE COD_PACIENTE = @CODIGO
      
      	DECLARE @ULTIMO_PACIENTE INT;
		SET @ULTIMO_PACIENTE = SCOPE_IDENTITY()
		RETURN @ULTIMO_PACIENTE ;

    END 	
    				
--------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_USUARIO @NOME VARCHAR(50), @LOGIN VARCHAR(15), @SENHA VARCHAR(10), 
							   @FUNCIONARIO INT, @DENTISTA INT, @TIPO BIT, @STATUS BIT, 
							   @DTHR_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_USUARIO 
		VALUES (@NOME, @LOGIN, @SENHA, @FUNCIONARIO, @DENTISTA, @TIPO, @STATUS, @DTHR_CADASTRO)
		DECLARE @ULTIMO_U INT;
		SET @ULTIMO_U = SCOPE_IDENTITY()
		RETURN @ULTIMO_U ;
	END

GO 

	EXEC GRAVA_USUARIO 'RENATA', 'DA', 'DA', NULL, 1, 1, 1, '20180628 11:36:34'
GO

	EXEC GRAVA_USUARIO 'MICHELE', 'MI', 'MI', 1, NULL, 1, 1, '20181103 14:03:58'
GO

	EXEC GRAVA_USUARIO 'AMANDA', 'MA', 'MA', 2, NULL, 0, 1, '20181013 09:23:45'
GO

	EXEC GRAVA_USUARIO 'JOAQUIM', 'JOAQUIM', 'JOA123', 4, NULL, 0, 0, '20180825 15:25:03'
GO

	EXEC GRAVA_USUARIO 'FLÁVIA', 'FLAVINHA', 'AIVALF', 3, NULL, 1, 0, '20180731 07:54:20'

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_USUARIO @CODIGO INT,@NOME VARCHAR(50), @LOGIN VARCHAR(15), @SENHA VARCHAR(10), 
							   @FUNCIONARIO INT, @DENTISTA INT, @TIPO BIT, @STATUS BIT
AS
	BEGIN
	   UPDATE TB_USUARIO
	   SET NOME_USUARIO = @NOME, LOGIN_USUARIO = @LOGIN, SENHA_USUARIO = @SENHA, FUNCIONARIO_USUARIO=@FUNCIONARIO, DENTISTA_USUARIO=@DENTISTA,
	       TIPO_USUARIO = @TIPO, STATUS_USUARIO = @STATUS
	   WHERE COD_USUARIO = @CODIGO
	END
		 	
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE GRAVA_AGENDAMENTO @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, 
								   @CONSULTA BIT, @OBS TEXT, @DTHORA_CADASTRO DATETIME
AS	
	BEGIN
		INSERT INTO TB_AGENDAMENTO
		VALUES (@DATAHORA, @PACIENTE, @DENTISTA, @TRATAMENTO, @CONSULTA, @OBS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_AG INT;
		SET @ULTIMO_AG = SCOPE_IDENTITY()
		RETURN @ULTIMO_AG ;
	END

GO

	EXEC GRAVA_AGENDAMENTO  '20190213 12:00:00', 1, 1, 1, 0, NULL, '20180627 17:33:24'
GO

	EXEC GRAVA_AGENDAMENTO  '20181222 13:30:00', 9, 7, 5, 0, NULL, '20181110 10:32:05'
GO

	EXEC GRAVA_AGENDAMENTO  '20190429 09:00:00', 6, 5, 3, 0, NULL, '20181023 09:15:46'
GO

	EXEC GRAVA_AGENDAMENTO  '20181130 15:30:00', 4, 8, 1, 0, NULL, '20180930 14:23:06'
GO

	EXEC GRAVA_AGENDAMENTO  '20190305 10:30:00', 2, 3, 4, 0, NULL, '20180821 12:05:23'
GO

	EXEC GRAVA_AGENDAMENTO  '20190601 08:00:00', 7, 4, 2, 0, NULL, '20181001 15:11:08'

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GO

CREATE PROCEDURE GRAVA_CONSULTA @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, 
								@PREAGENDADO INT, @OBS TEXT, @DTHORA_CADASTRO DATETIME
AS 
	BEGIN
		INSERT INTO TB_CONSULTA
		VALUES (@DATAHORA, @PACIENTE, @DENTISTA, @TRATAMENTO, @PREAGENDADO, @OBS, @DTHORA_CADASTRO)
		DECLARE @ULTIMA_CONS INT;
		SET @ULTIMA_CONS = SCOPE_IDENTITY()
		RETURN @ULTIMA_CONS ;
	END

GO

	EXEC GRAVA_CONSULTA '20190225 10:00:00', 2, 1, 3, NULL, NULL, '20181121 14:50:00' 
GO

	EXEC GRAVA_CONSULTA '20181222 13:30:00', 9, 7, 5, 2, NULL, '20181222 13:31:04'
GO

	EXEC GRAVA_CONSULTA '20181229 16:24:49', 1, 3, 4, NULL, NULL, '20181121 09:08:13'
GO

	EXEC GRAVA_CONSULTA '20181130 15:30:00', 4, 8, 1, 4, NULL, '20181130 14:32:34'
GO

	EXEC GRAVA_CONSULTA '20190601 08:00:00', 7, 4, 2, 6, NULL, '20181201 10:42:01'
GO

	EXEC GRAVA_CONSULTA '20181030 09:23:54', 3, 2, 4, NULL, NULL, '20181030 09:23:59'

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GO

CREATE PROCEDURE GRAVA_PRODUTO @NOME VARCHAR(15), @DENTISTA INT, @PRECO_UNITARIO MONEY, @TIPO VARCHAR(15), @VALIDADE DATE, 
							   @DATA_PAGAMENTO DATE, @QUANTIA INT, @TOTAL MONEY, @DTHORACADASTRO_PRODUTO DATETIME

AS
	BEGIN
		INSERT INTO TB_PRODUTO
		VALUES (@NOME, @DENTISTA, @PRECO_UNITARIO, @TIPO, @VALIDADE, @DATA_PAGAMENTO, @QUANTIA, @TOTAL, @DTHORACADASTRO_PRODUTO)
		
		DECLARE @ULTIMO_COD_PRODUTO INT;
		SET @ULTIMO_COD_PRODUTO = SCOPE_IDENTITY()
		RETURN @ULTIMO_COD_PRODUTO ;
	END

GO

	EXEC GRAVA_PRODUTO 'PINÇA CLÍNICA', 2, 14.52, 'INSTRUMENTO', NULL, '2018-11-26', 5, 72.6, '20181126 13:51:42'
GO

	EXEC GRAVA_PRODUTO 'PAPEL HIGIENICO', 3, 30.45, 'HIGIENE', NULL, '2018-11-27', 2, 60.9, '20181126 14:03:29'
GO

	EXEC GRAVA_PRODUTO 'CAFÉ', 5, 12, 'ALIMENTO', '2019-04-20', '2018-11-25', 3, 36, '20181126 14:00:36'
GO

	EXEC GRAVA_PRODUTO 'ESPELHO', 8, 23.15, 'INSTRUMENTO', NULL, '2018-11-26', 5, 115.75, '20181126 13:58:02'
GO

	EXEC GRAVA_PRODUTO 'MÁSCARA', 1, 12.35, 'DESCARTÁVEIS', NULL, '2018-11-20', 3, 37.05, '20181126 14:06:56'
GO

	EXEC GRAVA_PRODUTO 'LUSTRA MÓVEIS', 7, 4.99, 'LIMPEZA', NULL, '2018-11-25', 2, 9.98, '20181126 14:15:04'
GO

	EXEC GRAVA_PRODUTO 'BOLACHA', 4, 3.43, 'ALIMENTO', '2019-03-30', '2018-11-28', 4, 13.72, '20181126 14:10:02'
GO

	EXEC GRAVA_PRODUTO 'ESCAVADOR', 6, 25, 'INSTRUMENTO', NULL, '2018-11-19', 5, 125, '20181126 14:14:47'

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PRODUTO @CODIGO INT, @NOME VARCHAR(15), @PRECO_UNITARIO MONEY, @TIPO VARCHAR(15), @DENTISTA INT, 
								@VALIDADE DATE, @QUANTIA INT, @DTHORACADASTRO DATETIME, @DATA_PAG DATE, @TOTAL MONEY
AS
	BEGIN
	   UPDATE TB_PRODUTO
	   SET NOME_PRODUTO = @NOME, DENTISTA_PRODUTO=@DENTISTA ,PRECOUNITARIO_PRODUTO = @PRECO_UNITARIO, TIPO_PRODUTO = @TIPO, 
		   VALIDADE_PRODUTO = @VALIDADE, DATAPAGAMENTO_PRODUTO=@DATA_PAG ,QUANTIA_PRODUTO = @QUANTIA, TOTAL_PRODUTO=@TOTAL ,DTHORACADASTRO_PRODUTO = @DTHORACADASTRO
	   WHERE COD_PRODUTO = @CODIGO
	END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_DESPESA @TIPO VARCHAR(15), @PRODUTO INT, @PAG_FUNC INT, @PAG_DENT INT, @VALOR MONEY, @DATAPAGAMENTO DATE, @OBS TEXT, @DTHORACADASTRO_DESPESA DATETIME
AS
	BEGIN
		INSERT INTO TB_DESPESA
		VALUES(@TIPO, @PRODUTO, @PAG_FUNC, @PAG_DENT, @VALOR, @DATAPAGAMENTO, @OBS, @DTHORACADASTRO_DESPESA)		
		DECLARE @ULTIMO_COD_DESPESA INT;
		SET @ULTIMO_COD_DESPESA = SCOPE_IDENTITY()
		RETURN @ULTIMO_COD_DESPESA ;
	END 

GO

	EXEC GRAVA_DESPESA 'PRODUTO', 2, NULL, NULL, 60.9, '2018-11-27', NULL, '20181126 14:03:29'
GO

	EXEC GRAVA_DESPESA 'ÁGUA', NULL, NULL, NULL, 92.56, '2018-10-02', NULL, '20181002 14:36:56'
GO

	EXEC GRAVA_DESPESA 'PRODUTO', 1, NULL, NULL, 60.9, '2018-11-27', NULL, '20181126 13:51:42'
GO

	EXEC GRAVA_DESPESA 'PRODUTO', 4, NULL, NULL, 115.75, '2018-11-26', NULL, '20181126 13:58:02'
GO

	EXEC GRAVA_DESPESA 'ENERGIA', NULL, NULL, NULL, 115.21, '2018-11-13', NULL, '20181114 15:06:29'
GO

	EXEC GRAVA_DESPESA 'PRODUTO', 5, NULL, NULL, 37.05, '2018-11-20', NULL, '20181126 14:06:56'
GO

	EXEC GRAVA_DESPESA 'PRODUTO', 7, NULL, NULL, 13.72, '2018-11-28', NULL, '20181126 14:10:02'
GO

	EXEC GRAVA_DESPESA 'INTERNET', NULL, NULL, NULL, 80.32, '2018-10-31', NULL, '20181102 09:20:54'
GO

	EXEC GRAVA_DESPESA 'PRODUTO', 8, NULL, NULL, 125, '2018-11-19', NULL, '20181126 14:14:47'
GO

	EXEC GRAVA_DESPESA 'ALUGUEL', NULL, NULL, NULL, 695, '2018-10-25', NULL, '20181101 18:23:06'
GO

	EXEC GRAVA_DESPESA 'PRODUTO', 6, NULL, NULL, 9.98, '2018-11-25', NULL, '20181126 14:15:04'
GO

	EXEC GRAVA_DESPESA 'PRODUTO', 3, NULL, NULL, 36, '2018-11-25', NULL, '20181126 14:00:36'

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_DESPESA @CODIGO INT, @TIPO VARCHAR(15), @VALOR MONEY, @DATAPAGAMENTO DATE, @OBS TEXT, @DTHORACADASTRO DATETIME
AS
	BEGIN
	   UPDATE TB_DESPESA
	   SET TIPO_DESPESA = @TIPO, VALOR_DESPESA = @VALOR, DATAPAGAMENTO_DESPESA = @DATAPAGAMENTO, 
	       OBS_DESPESA = @OBS, DTHORACADASTRO_DESPESA = @DTHORACADASTRO
	   WHERE COD_DESPESA = @CODIGO   	
	   	DECLARE @ULTIMO_COD_DESPESA INT;
		SET @ULTIMO_COD_DESPESA = SCOPE_IDENTITY()
		RETURN @ULTIMO_COD_DESPESA ;
	END
	

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PAGAMENTO_PACIENTE_AVISTA @PACIENTE INT, @DENTISTA INT, 
												 @VALOR MONEY, @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), @STATUS BIT,
												 @DTHORA_CADASTRO DATETIME
AS
	BEGIN
	
		INSERT INTO TB_PAGAMENTO_PACIENTE_AVISTA
		VALUES(@PACIENTE, @DENTISTA, @VALOR, @DATAPAGAMENTO, @TIPO, @STATUS, @DTHORA_CADASTRO)		
		DECLARE @ULTIMO_COD_AVISTA INT;
		SET @ULTIMO_COD_AVISTA = SCOPE_IDENTITY() -- funcionando
		RETURN @ULTIMO_COD_AVISTA ;
		
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

create PROCEDURE ALTERA_PAGAMENTO_PACIENTE_AVISTA @CODIGO INT, @PACIENTE INT, @DENTISTA INT, @VALOR MONEY, 
												  @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), @STATUS BIT
AS
	BEGIN
       UPDATE TB_PAGAMENTO_PACIENTE_AVISTA
       SET PACIENTE_AVISTA = @PACIENTE, DENTISTA_AVISTA = @DENTISTA, VALOR_AVISTA = @VALOR, 
	       DATAPAGAMENTO_AVISTA = @DATAPAGAMENTO, TIPO_AVISTA = @TIPO, STATUS_PAGAMENTO = @STATUS 
       WHERE COD_AVISTA = @CODIGO
	   DECLARE @ULTIMO_ALT_AVISTA INT;
	   SET @ULTIMO_ALT_AVISTA = SCOPE_IDENTITY() -- funcionando
	   RETURN @ULTIMO_ALT_AVISTA ;
    END


GO

CREATE PROCEDURE ALTERA_PAGAMENTO_PACIENTE_APRAZO @CODIGO INT, @PACIENTE INT, @DENTISTA INT, @VALOR MONEY, 
												  @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), @OBS TEXT, @STATUS BIT
AS
	BEGIN
       UPDATE TB_PAGAMENTO_PACIENTE_APRAZO
       SET PACIENTE_APRAZO = @PACIENTE, DENTISTA_APRAZO = @DENTISTA, VALOR_APRAZO = @VALOR, 
	       DATAPAGAMENTO_APRAZO = @DATAPAGAMENTO, TIPO_APRAZO = @TIPO, OBS_APRAZO = @OBS ,STATUS_PAGAMENTO = @STATUS 
       WHERE COD_APRAZO = @CODIGO
	   DECLARE @ULTIMO_ALT_AP INT;
	   SET @ULTIMO_ALT_AP = SCOPE_IDENTITY() 
	   RETURN @ULTIMO_ALT_AP ;
    END
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PAGAMENTO_PACIENTE_PARCELADO @PACIENTE INT, @DENTISTA INT, @TIPO VARCHAR(15), @VALOR_TOTAL MONEY, 
													@QUANTIA INT, @OBS TEXT, @DTHORA_CADASTRO DATETIME 
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_PACIENTE_PARCELADO
		VALUES(@PACIENTE, @DENTISTA, @TIPO, @VALOR_TOTAL, @QUANTIA, @OBS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_PARCELAMENTO INT
		SET @ULTIMO_PARCELAMENTO = SCOPE_IDENTITY()
		RETURN @ULTIMO_PARCELAMENTO

	END

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PARCELAS @COD_PARCELAMENTO INT, @DATAPAGAMENTO DATE, @DATAVENCIMENTO DATE, @ENTRADA BIT, @VALOR MONEY, @DESCONTO MONEY,
								@STATUS_PARCELA BIT, @OBS TEXT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PARCELA
		VALUES(@COD_PARCELAMENTO, @DATAPAGAMENTO, @DATAVENCIMENTO, @ENTRADA, @VALOR, @DESCONTO, @STATUS_PARCELA, @OBS, @DTHORA_CADASTRO)
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE GRAVA_PAGAMENTO_PACIENTE_APRAZO @PACIENTE INT, @DENTISTA INT, @VALOR MONEY, @DATAPAGAMENTO DATE, @TIPO VARCHAR(15), 
												 @OBS TEXT, @STATUS BIT, @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_PACIENTE_APRAZO 
		VALUES (@PACIENTE, @DENTISTA, @VALOR, @DATAPAGAMENTO, @TIPO, @OBS, @STATUS ,@DATAPAGAMENTO)
		DECLARE @ULTIMO_AP INT
		SET @ULTIMO_AP = SCOPE_IDENTITY()
		RETURN @ULTIMO_AP
	END
	
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE GRAVA_PAGAMENTO_FUNCIONARIO @COD_FUNCIONARIO INT, @VALOR_FIXO MONEY, @VALOR_EXTRA MONEY, @TOTAL MONEY, @DATA DATE, @STATUS BIT , @DTHORA_CADASTRO DATETIME
AS
	BEGIN
		INSERT INTO TB_PAGAMENTO_FUNCIONARIO
		VALUES(@COD_FUNCIONARIO, @VALOR_FIXO, @VALOR_EXTRA, @TOTAL, @DATA, @STATUS, @DTHORA_CADASTRO)
		DECLARE @ULTIMO_PF INT
		SET @ULTIMO_PF = SCOPE_IDENTITY()
		RETURN @ULTIMO_PF
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PAGAMENTO_FUNCIONARIO @CODIGO INT,  @COD_FUNCIONARIO INT, @VALOR_FIXO MONEY, @VALOR_EXTRA MONEY, 
											  @TOTAL MONEY, @DATA DATE, @STATUS BIT
AS
    BEGIN
       UPDATE TB_PAGAMENTO_FUNCIONARIO
	   SET COD_FUNCIONARIO_PAGAMENTO=@COD_FUNCIONARIO, VALORFIXO_PAGAMENTO=@VALOR_FIXO, 
	   VALOREXTRA_PAGAMENTO=@VALOR_EXTRA, TOTAL_PAGAMENTO=@TOTAL, DATA_PAGAMENTO=@DATA, STATUS_PAGAMENTO=@STATUS
       WHERE COD_PAGAMENTO = @CODIGO 
       DECLARE @ULTIMO_PF INT
	   SET @ULTIMO_PF = SCOPE_IDENTITY()
	   RETURN @ULTIMO_PF
    END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_AGENDAMENTO, TB_DENTISTA, TB_PACIENTE, TB_TRATAMENTO
WHERE COD_DENTISTA=DENTISTA_AGENDAMENTO AND COD_PACIENTE=PACIENTE_AGENDAMENTO AND COD_TRATAMENTO=TRATAMENTO_AGENDAMENTO

GO

CREATE PROCEDURE ALTERA_AGENDAMENTO_BIT @CODIGO INT
AS
	BEGIN 	
		UPDATE TB_AGENDAMENTO SET CONSULTA_AGENDAMENTO=1 WHERE COD_AGENDAMENTO = @CODIGO
	END	
	
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO

CREATE PROCEDURE GRAVA_LOG @DESCRICAO TEXT, @USUARIO INT, @DTHORA DATETIME 
AS
	BEGIN
		INSERT INTO TB_LOG
		VALUES(@DESCRICAO, @USUARIO, @DTHORA)
	END

----------------------------------------------------------------------------------------------------------------------------------------------------------------	

GO

CREATE PROCEDURE CAIXA_AUTOMATICO @DATA DATE,@ENTRADA MONEY,@SAIDA MONEY,@DTCADASTRO DATETIME,@AVISTA INT,@APRAZO INT,@PARCELA INT,@DESPESA INT
AS
DECLARE @ENTRADAS MONEY, @SAIDAS MONEY, @SOMA MONEY
	BEGIN
		
		SET @ENTRADAS = ( SELECT SUM(ENTRADA_CAIXA)		FROM TB_CAIXA WHERE CAST(DTCADASTRO_CAIXA AS DATE) = @DATA);             
		
		SET @SAIDAS =	( SELECT SUM(SAIDA_CAIXA)		FROM TB_CAIXA WHERE CAST(DTCADASTRO_CAIXA AS DATE) = @DATA);
		
		
		---
		IF (@ENTRADAS is NULL) and (@SAIDAS is NULL)
		BEGIN
			SET @SOMA = @ENTRADA-@SAIDA;
	        select @soma;
		    INSERT INTO TB_CAIXA VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);
	    END
	   
	    
	    ELSE IF (@ENTRADAS is not NULL) and (@SAIDAS is NULL)
	    BEGIN
			SET @SOMA = @ENTRADAS + (@ENTRADA - @SAIDA)
		    INSERT INTO TB_CAIXA
		    VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);	    
	    END
	   
	    ---
	    ELSE IF (@ENTRADAS is NULL) and (@SAIDAS is not NULL)
	    BEGIN
			SET @SOMA = @SAIDAS + (@ENTRADA - @SAIDA)
		    INSERT INTO TB_CAIXA
		    VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);	    
	    END 
	   
	    ---
	    ELSE
	    BEGIN
			SET @SOMA = (@ENTRADAS - @SAIDAS) + @ENTRADA-@SAIDA;
		    INSERT INTO TB_CAIXA
		    VALUES(@ENTRADA, @SAIDA, @SOMA, @DTCADASTRO, @AVISTA, @APRAZO, @PARCELA, @DESPESA);
		END
		
END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PAGAMENTO_DENTISTA @CODIGO_PAGAMENTO INT, @CODIGO_DENT INT, @VALOR MONEY, @DATA DATE, @STATUS BIT
AS
	BEGIN	
		UPDATE TB_PAGAMENTO_DENTISTA
		SET COD_DENTISTA=@CODIGO_DENT, VALOR_PAGAMENTO=@VALOR, DATA_PAGAMENTO=@DATA,STATUS_PAGAMENTO=@STATUS
		WHERE COD_PAGAMENTO=@CODIGO_PAGAMENTO 
	END 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	SELECT * FROM TB_AGENDAMENTO
GO

CREATE PROCEDURE ALTERA_AGENDAMENTO @CODIGO INT, @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, @CONSULTA BIT, @OBS TEXT
AS
BEGIN
	UPDATE TB_AGENDAMENTO SET DATAHORA_AGENDAMENTO=@DATAHORA, PACIENTE_AGENDAMENTO=@PACIENTE, DENTISTA_AGENDAMENTO=@DENTISTA, 
		TRATAMENTO_AGENDAMENTO=@TRATAMENTO,	CONSULTA_AGENDAMENTO=@CONSULTA, OBS_AGENDAMENTO=@OBS WHERE COD_AGENDAMENTO=@CODIGO
END

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE EXCLUI_CAIXA @CODIGO INT
AS
BEGIN
	DELETE TB_CAIXA WHERE DESPESAS_CAIXA=@CODIGO
END
	
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE EXCLUI_DESPESA @CODIGO INT
AS
BEGIN
	DELETE TB_DESPESA WHERE COD_DESPESA=@CODIGO
END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO 

CREATE PROCEDURE ALTERA_CONSULTA @CODIGO INT, @DATAHORA DATETIME, @PACIENTE INT, @DENTISTA INT, @TRATAMENTO INT, @OBS TEXT
AS
BEGIN
	UPDATE TB_CONSULTA SET DATAHORA_CONSULTA=@DATAHORA, PACIENTE_CONSULTA=@PACIENTE, DENTISTA_CONSULTA=@DENTISTA,
						   TRATAMENTO_CONSULTA=@TRATAMENTO, OBS_CONSULTA=@OBS
	WHERE COD_CONSULTA=@CODIGO
END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE PAGA_FUNCIONARIO @CODIGO INT
AS
	BEGIN
		UPDATE TB_PAGAMENTO_FUNCIONARIO SET STATUS_PAGAMENTO=1 WHERE COD_PAGAMENTO=@CODIGO
	END
    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE PAGAMENTO_FUNC_EX @CODIGO INT 
AS
		DECLARE @PAGAMENTO INT, @CAIXA INT, @DESPESA INT
	BEGIN
		
		SET @DESPESA = ( SELECT COD_DESPESA FROM TB_DESPESA, TB_PAGAMENTO_FUNCIONARIO WHERE COD_PAGAMENTO=PAG_FUNCIONARIO
						AND COD_PAGAMENTO=@CODIGO )
		SET @CAIXA   = ( SELECT COD_CAIXA FROM TB_CAIXA, TB_DESPESA WHERE COD_DESPESA=DESPESAS_CAIXA AND 
						DESPESAS_CAIXA = @DESPESA )
		
		DELETE TB_CAIXA					WHERE COD_CAIXA=@CAIXA
		DELETE TB_DESPESA				WHERE COD_DESPESA=@DESPESA
		DELETE TB_PAGAMENTO_FUNCIONARIO WHERE COD_PAGAMENTO=@CODIGO
	
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	
GO
	
CREATE PROCEDURE PAGAMENTO_DENT_EX @CODIGO INT 
AS
		DECLARE @PAGAMENTO INT, @CAIXA INT, @DESPESA INT
	BEGIN
		
		SET @DESPESA = ( SELECT COD_DESPESA FROM TB_DESPESA, TB_PAGAMENTO_DENTISTA WHERE COD_PAGAMENTO=PAG_DENTISTA
						AND COD_PAGAMENTO=@CODIGO )
		SET @CAIXA   = ( SELECT COD_CAIXA FROM TB_CAIXA, TB_DESPESA WHERE COD_DESPESA=DESPESAS_CAIXA AND 
						DESPESAS_CAIXA = @DESPESA )
		
		DELETE TB_CAIXA					WHERE COD_CAIXA=@CAIXA
		DELETE TB_DESPESA				WHERE COD_DESPESA=@DESPESA
		DELETE TB_PAGAMENTO_DENTISTA	WHERE COD_PAGAMENTO=@CODIGO
	
	END	

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	
GO
	
CREATE PROCEDURE EXCLUI_AGENDAMENTO @CODIGO INT
AS
	BEGIN
	
		DELETE TB_CONSULTA WHERE PREAGENDAMENTO_CONSULTA = @CODIGO
		DELETE TB_AGENDAMENTO WHERE COD_AGENDAMENTO = @CODIGO
	
	END

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE EXCLUI_CONSULTA @CODIGO INT
AS
	BEGIN
		
		DELETE TB_CONSULTA WHERE COD_CONSULTA=@CODIGO
		
	END

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
GO
	EXEC GRAVA_TRATAMENTO 'IMPLANTODONTIA', NULL, '20181121 14:52:00'
GO 
	EXEC GRAVA_FUNCIONARIO 'MICHELE', 'F', '1997-09-19', '12.223.993-X', '39902811899', 'RUA AUGUSTA, 234', 'MICHELE@EXEMPLO.COM', 8886, '(00)00000-0000', '(00)00000-0000', 1, '20181027 22:48:20'
GO 
	EXEC GRAVA_FUNCIONARIO 'FRANCISCO', 'M', '1997-01-22', '13.234.443-D', '89347589993', 'RUA PAULISTA, 234', 'FRANCISCO@EXEMPLO.COM', 8886, '(00)00000-0000', '(00)00000-0000', 0, '20181027 22:48:56'
GO
	EXEC GRAVA_RESPONSAVEL 'BIANCA CARVALHO', '55.541.321-22',  '46693100899', 'F', '(14)33568-891',  'SITIO SÃO BERNARDO' , NULL, 8886, '1995-09-14', 1, '20180621 11:01:20.000'
GO 
	EXEC GRAVA_PACIENTE 'VICTÓRIA MARTINS', '12.178.458-7', '99886527048', 'F', '19800207', 'RUA SANTO ANTONIO, 138', NULL, 1813, '(14)99889-3056', NULL, 0, NULL, NULL, 1,  '20180628 11:36:34'   
GO
	EXEC GRAVA_PACIENTE 'ELIAS FERNANDO', '36.202.962-3', '17272375019', 'M', '19950416', 'RUA ÁGATA, 142', NULL, 1813, '(14)99889-3056', NULL, 0, NULL, NULL, 1,  '20180628 11:36:34'   
GO	
	EXEC GRAVA_AGENDAMENTO  '20190913 12:00:00', 1, 1, 1, 0, NULL, '20180627 17:33:24'
GO
	EXEC GRAVA_CONSULTA '20181211 13:30:00', 2, 1, 1, NULL, NULL, '20181121 14:50:00'*/


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

GO

CREATE PROCEDURE ALTERA_PRODUTO_CX_DP @CODIGO INT 
AS
		DECLARE @SAIDA_NOVA MONEY, @DESPESA INT--, @TOTAL_CAIXA MONEY, @SAIDA_ANTERIOR MONEY, @TOTAL_CAIXA_NOVO MONEY
	BEGIN
		
		SET @DESPESA = ( SELECT COD_DESPESA FROM TB_DESPESA, TB_PRODUTO WHERE COD_PRODUTO=PRODUTO_DESPESA
						 AND COD_PRODUTO=@CODIGO )
						
		SET @SAIDA_NOVA = (SELECT TOTAL_PRODUTO FROM TB_PRODUTO WHERE COD_PRODUTO=@CODIGO)
		
		UPDATE TB_CAIXA
		SET SAIDA_CAIXA = @SAIDA_NOVA
		WHERE DESPESAS_CAIXA = @DESPESA
		
		UPDATE TB_DESPESA
		SET VALOR_DESPESA = @SAIDA_NOVA
		WHERE PRODUTO_DESPESA = @CODIGO
	
	END

GO
	
CREATE PROCEDURE ALTERA_PARCELAS_PACIENTE @CODIGO INT, @COD_PARCELAMENTO INT, @DATAPAGAMENTO DATE, @DATAVENCIMENTO DATE, @ENTRADA BIT, @OBS TEXT
AS
	BEGIN
		UPDATE TB_PARCELA
		SET COD_PARCELAMENTO=@COD_PARCELAMENTO, DATAPAGAMENTO_PARCELA=@DATAPAGAMENTO, 
		DATAVENCIMENTO_PARCELA=@DATAVENCIMENTO, ENTRADA_PARCELA=@ENTRADA, OBS_PARCELA=@OBS 
		WHERE COD_PARCELA=@CODIGO
     END	

GO

CREATE PROCEDURE PAGA_PARCELAS_PACIENTE @CODIGO INT, @VALOR MONEY, @DESCONTO MONEY, @STATUS_PARCELA BIT, @DATA DATE --1=PAGO, 0=PENDENTE
										
AS
	BEGIN
		UPDATE TB_PARCELA
		SET  VALOR_PARCELA=@VALOR, DESCONTO_PARCELA=@DESCONTO, STATUS_PARCELA=@STATUS_PARCELA, DATAPAGAMENTO_PARCELA=@DATA
		WHERE COD_PARCELA=@CODIGO
     END	
